### ISSUE TITLE
How to generate Nodejs SDK with nestia using Nestjs swagger json url of Nestjs project? 

### ISSUE THREAD

**Issue by anshshah016** [samchon/nestia#1006]
I want to create an SDK from the Swagger JSON URL of my NestJS project's deployed backend. 
For example: https://demovoucherapi.ogstack.com/api/swagger-json.

When I generate the SDK using a Swagger JSON file, it works fine. However, if the JSON file changes (e.g., due to the addition of new endpoints in my NestJS project), I need to regenerate the SDK with the updated Swagger JSON file.

Is there a feature or tool that allows generating an SDK directly from the Swagger JSON URL? This way, even if there are changes in my project and the Swagger definition gets updated, I could rebuild the SDK using the same Swagger URL.

Additionally, if I generate the SDK using a Swagger JSON file, how can I rebuild the SDK if there are changes in that JSON file? Is there a way to automate the regeneration process whenever the Swagger JSON file is updated?

Is there any configuration we can add to the swagger.json file for proper method naming?

Looking forward to your response.
Thank you in advance!

**Comment by Tokirkhokhar** [comment]
I'm facing a similar challenge with my NestJS project and would like to contribute to the discussion.

I'm also looking for a way to create an SDK directly from the Swagger JSON URL of my deployed backend. Currently, I regenerate the SDK manually whenever there are changes to the Swagger JSON file, which is not ideal for maintaining consistency.

so Is there a feature or tool that allows generating an SDK directly from the Swagger JSON URL?

**Comment by samchon** [comment]
Now, you can insert URL value into the `@nestia/migrate`.

https://nestia.io/docs/migrate/
