### ISSUE TITLE
swagger output not satisfy open api spec

### ISSUE THREAD

**Issue by sacru2red** [samchon/nestia#1014]
## Bug Report
I have under code
```ts
import { type OpenAPIObject, SwaggerModule } from '@nestjs/swagger'
...
const docs = require(path.resolve(__dirname, '..', '..', 'swagger', 'swagger.json'))
const assertedDocs = assert<OpenAPIObject>(docs)
```
It throws error

debugging: validate result ->
```
{
  "success": false,
  "errors": [
    {
      "path": "$input.paths[\"/admin/administrator/all\"].get.responses[\"200\"]",
      "expected": "(ReferenceObject | ResponseObject)",
      "value": {
        "content": {
          "application/json": {
            "schema": {
              "$ref": "#/components/schemas/sersControllerResponseDto"
            }
          }
        }
      }
    },
```

ref0: https://github.com/OAI/OpenAPI-Specification/blob/3.0.0-rc0/versions/3.0.md#responseObject
-> description is Required
ref1: https://github.com/nestjs/swagger/blob/master/lib/interfaces/open-api-spec.interface.ts
ref2: https://swagger.io/specification/#paths-object
```
  responses:
    NotFound:
      description: Entity not found.
    IllegalInput:
      description: Illegal input for operation.
    GeneralError:
      description: General Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GeneralError'
```

**Comment by samchon** [comment]
In `@nestjs/swagger`, how to fill the `description` property value?

**Comment by samchon** [comment]
I've researched many other OpenAPI documents to develop `@nestia/migrate` and `@nestia/editor`, but most of famous services have not filled the `description` field for media type of the body. Therefore, I've designed both `OpenApi.IOperation.IRequestBody.description` and `OpenApi.IOperation.IResponse.description` properties as optional.

  - OpenAPI definition
    - https://github.com/samchon/openapi/blob/master/src/OpenApi.ts#L562
    - https://github.com/samchon/openapi/blob/master/src/OpenApi.ts#L574
  - OpenAPI generator
    - `@nestia/editor`: https://nestia.io/docs/editor/
    - `@nestia/migrate`: https://nestia.io/docs/migrate/

In such reason, I've guided to cast the `@nestia/sdk` generated OpenAPI document to be `any` in the guide documents:

  - https://nestia.io/docs/sdk/swagger/#bootstrap

**Comment by samchon** [comment]
However, even though many other major services are not filling the `description` property, I do not need to do like them.

If no `@return` or `@returns` comment exists in the controller method, I'll fill the `description` property as empty string `""`.

**Comment by sacru2red** [comment]
Thanks for quick response!

**Comment by sacru2red** [comment]
음 마지막 줄을 못보고 이슈를 닫아버렸네요.
아마? 진행하신다면 다시 오픈하셔야 할 것 같습니다ㅎㅎ..

빈 문자열로 채우는 것도 괜찮은 것 같아요. 아니면 엔티티 이름이 적당한 길이 이상이면 엔티티 이름을 박아도 되지 않을까 잠깐 생각해봤습니다.

**Comment by samchon** [comment]
Also, you don't have to validate through the OpenAPI definition of `@nestia/swagger`.

It's version is 3.0 only, but `@nestia/sdk` is supporting every versions' generation.

  - v2.0
  - v3.0
  - v3.1

**Comment by samchon** [comment]
Upgrade to v3.12.2, then be fixed.
