### ISSUE TITLE
Want to display parameter examples in Swagger documentation generated by Nestia

### ISSUE THREAD

**Issue by shad0xfox** [samchon/nestia#1031]
I'm using Nestia to generate Swagger documentation, but I'm unable to display example values for parameters in the generated docs.

I tried `@example`
``` js
interface IGetHello {
  /**
   * @example test
   */
  name: string;
}
```
I'm looking for an effect similar to NestJS's @ApiProperty({ example: 'test' }).

I've searched through the issues but haven't found any similar questions.
I also couldn't find any information in the documentation about setting parameter examples.
Am I missing something? Thank you for your help.

**Comment by samchon** [comment]
Not supporting nested property level example.

If you want it, you have to do it like below.

```typescript
import typia, { tags } from "typia";

interface IGetHello {
  name: string & tags.Plugin<{
    example: "test"
  }>;
}
```

**Comment by shad0xfox** [comment]
Hi @samchon,

Thank you for your suggestion!
I implemented your method and tried the code below, it solved the issue perfectly.

```js
interface IGetHello {
  name: string &
    tags.JsonSchemaPlugin<{
      example: 'test';
    }>;
}
```


I really appreciate your help.
