### ISSUE TITLE
How can I change the response content-type of my sdk?

### ISSUE THREAD

**Issue by Iuriiiii** [samchon/nestia#1046]
Hi! I tried Nestia for a interesting personal project, i created the endpoint `health` that returns a single `!` character on `text/plain` format

How can I tell Nestia to make this specific endpoint to be a different content type than `application/json`?

**Comment by samchon** [comment]
`@TypedRoute.Get()` supports only `application/json` type.

If you want other thing, just use NestJS's original `@Get()` decorator.

**Comment by Iuriiiii** [comment]
Thanks for your quick answer! I'm using NestJS decorators
![image](https://github.com/user-attachments/assets/a42c7be9-1613-477b-a3c7-034a430db8cc)

May Nestia not ready to handle other content-type than app/json yet?

**Comment by Iuriiiii** [comment]
I'll close this question then! Thanks for you job! This project is amazing, i'll try to send you a pr to solve this detail!

**Comment by samchon** [comment]
Current `@nestia/sdk` supports the `@Header("Content-Type", "text/plain")` decorator, but I've forgotten the `@ApiProduces()`.

I'll make it to be supported.
