### ISSUE TITLE
Issue with @default Tag in Latest Nestia Version and Swagger Generation

### ISSUE THREAD

**Issue by ohjiwan-oj** [samchon/nestia#1063]
### Describe the bug

In previous versions, the `@default tag was successfully converted to the default value in Swagger. However, it seems that in the latest version, this conversion is no longer working.

```
export interface ICreateUserRequestDto {
  /**
   * User's email address
   * 
   * @pattern [a-zA-Z0-9@.]+$
   * @maxLength 320
   * @default user@example.com
   * 
   */
  email: string;

  /**
   * Social network service type
   * 
   * @default KAKA
   */
  snsType: SnsType;

  /**
   * Social network service ID
   *
   * @default 1234567890
   */
  snsId: string;
}

```

After writing the code as above and generating the swagger.json file using the nestia swagger command, the default fields are no longer appearing in the latest version.

```
"ICreateUserRequestDto": {
    "type": "object",
    "properties": {
      "email": {
        "type": "string",
        "maxLength": 320,
        "pattern": "[a-zA-Z0-9@.]+$",
        "default": "user@example.com",
        "description": "User's email address"
      },
```

I spent over five hours trying to find the cause in the code. When I reverted to the previous working version, 5.3.0, the default fields like "default": "user@example.com" were correctly generated.

Has the `@default tag functionality been removed in the new version, or is this a bug?

### Expected behavior

I expected the `@default tag to be converted in the Swagger documentation, with the expected default values included for each field

```
"ICreateUserRequestDto": {
    "type": "object",
    "properties": {
      "email": {
        "type": "string",
        "maxLength": 320,
        "pattern": "[a-zA-Z0-9@.]+$",
        "description": "User's email address"
      },
      "snsType": {
        "type": "string",
        "enum": [
          "APPLE",
          "GOOGLE",
          "KAKAO"
        ],
        "description": "Social network service type"
      },
      "snsId": {
        "type": "string",
        "description": "Social network service ID"
      }
    },
    "nullable": false,
    "required": [
      "email",
      "snsType",
      "snsId"
    ],
    "description": "User creation request DTO"
  }

```

### Actual behavior

The `@default tag is not being converted in the Swagger documentation, and the default values are not included for any of the fields.

**Comment by samchon** [comment]
The comment tag `@default` has never been formalized in the documentation, nor has it ever been explicitly supported.

**Comment by kolbacer** [comment]
> The comment tag `@default` has never been formalized in the documentation, nor has it ever been explicitly supported.

Hello, what did you mean by that? The `@default` tag is mentioned in both [nestia](https://nestia.io/docs/sdk/swagger/#dto-properties) and [typia](https://typia.io/docs/json/schema/#specialization) documentations as well as in the [swagger](https://swagger.io/docs/specification/v3_0/describing-parameters/#default-parameter-values) docs. You also implemented this feature a couple of years ago: https://github.com/samchon/typia/issues/211.

As for now, I observe the following behavior (`nestia` v6.3.1, `@nestia/core` & `sdk` v4.6.1, `typia` v7.6.0):
- `Default` **type tag** is working everywhere
- `@default` **comment tag** is not working

Could you please clarify if this is a bug or I am missing something? Thanks!

**Comment by ohjiwan-oj** [comment]
Hmm... Anyway, I am using the @default tag when defining DTOs, like this:
typescript
```
/**
 * Simple inquiry password
 * @minLength 8
 * @maxLength 20
 * @default banking_pass_123
 */
  bankingPassword?: string;
```
```

swagger Example Value
{
  "accountId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
  "bankType": "KB",
  "accountNumber": "100-212-345678-9",
  "accountHolder": "홍길동",
  "accountType": "PERSONAL",
  "accountPassword": "1234",
  "bankingId": "bank_user_01",
  "bankingPassword": "banking_pass_123",
  "identityNumber": "146-88-43244",
  "useAutoSearch": true
}
```

When I do this, the value appears in the Example Value section of Swagger.
I’m not sure why, but this behavior works perfectly fine with "nestia": "^5.3.0". However, it doesn’t work in later versions.
I’ve actually been using the @default functionality with "nestia": "^5.3.0" for several months without any issues.
Although I can’t figure out the exact cause, I’ve experienced this behavior: it doesn’t work in the latest version, but when I downgrade the version, it works as expected.

**Comment by ohjiwan-oj** [comment]
It took me a week to identify this issue.
Moreover, the official documentation provides examples like the one below, which naturally led me to believe that this feature was supported.
```

export interface SpecialTag {
  /**
   * Deprecated tags are just used for marking.
   *
   * @title Unsigned integer
   * @deprecated
   */
  type: number & tags.Type<"uint32">;
 
  /**
   * Internal tagged property never be shown in JSON schema.
   *
   * It even doesn't be shown in other `typia` functions like `assert<T>()`.
   *
   * @internal
   */
  internal: number[];
 
  /**
   * Hidden tagged property never be shown in JSON schema.
   *
   * However, it would be shown in other `typia` functions like `stringify<T>()`.
   *
   * @hidden
   */
  hidden: boolean;
 
  /**
   * You can limit the range of number.
   *
   * Also, you can configure `default` property by comment tag.
   *
   * @default 30
   */
  number?: number & tags.ExclusiveMinimum<19> & tags.Maximum<100>;
 
  /**
   * You can limit the length of string.
   */
  string: string & tags.MinLength<3>;
 
  /**
   * You can limit the pattern of string.
   */
  pattern: string & tags.Pattern<"^[a-z]+$">;
 
  /**
   * You can limit the format of string.
   */
  format: null | (string & tags.Format<"date-time">);
 
  /**
   * You also can perform union type in type tags.
   */
  ip: string & (tags.Format<"ipv4"> | tags.Format<"ipv6">);
 
  /**
   * In the Array case, only type tags can limit elements' type.
   */
  array: Array<string & tags.Format<"uuid">> &
    tags.MinItems<3> &
    tags.MaxItems<100>;
}

```
This made me think it’s definitely supported.
If it’s not, I’ll take your word for it and move on. But this is the behavior I’ve encountered.
