### ISSUE TITLE
Support error custom message

### ISSUE THREAD

**Issue by thoriqadillah** [samchon/nestia#1064]
I'm using nestia ^3.2.1, and the current error message is a bit too verbose. I'm aware that you can't add error message because the possibilities is infinite as stated in #886 

but, what if you introduce new tag instead for the custom error message such as
```ts
interface Foo {
  bar: string & tags.Message<"Bar is required">
}
```
or
```ts
interface Foo {
  bar: number & tags.Max<3, "Maximum number is 3">
}
```
so there is no need to check the possibilities. if the message is defined, always fallback to the custom one

**Comment by thoriqadillah** [comment]
i think this is more on the typia itself rather than nestia. should i duplicate this issue in typia? @samchon

**Comment by samchon** [comment]
Too much repeated in both `typia` and `nestia`, and my answer is always "no plan to support".

The error message is composed by various combinations, and its number of cases is infinite. Human can't write it manually.

https://github.com/samchon/typia/issues/1300

**Comment by rivatove** [comment]
> Too much repeated in both `typia` and `nestia`, and my answer is always "no plan to support".
> 
> The error message is composed by various combinations, and its number of cases is infinite. Human can't write it manually.
> 
> [samchon/typia#1300](https://github.com/samchon/typia/issues/1300)

@samchon I don't think disregarding the issue completely is productive.

`export type Email = string & tags.Format<'email'>;`

I'm using this type and the returned error message is: `Request body data is not following the promised type.` This is in no way useful to the end user of the application. Maybe add an extra `message` argument to the tags.Format<_format_, _message_> type?
