### ISSUE TITLE
Branded types support

### ISSUE THREAD

**Issue by rivatove** [samchon/nestia#1066]
## Feature Request
  
Nestia throws the following error on branded properties:
```
- number & Brand<"ProductPrice">:
- nonsensible intersection
```

With the `ProductPrice` being of the following type (with a standard `Branded` implementation):
```ts
type ProductPrice = Branded<number, 'ProductPrice'>;
```

I wonder if there is a way for Nestia to reduce the above type to just number?

Maybe we could somehow define the `Brand` wrapper to make Nestia ignore intersections with that type? Or to define the internal brand property key (in my case `__brand`) to ignore?

**Comment by samchon** [comment]
Branded type is not supported, because it needs hard type casting, not type safe strategy.

**Comment by rivatove** [comment]
> Branded type is not supported, because it needs re-interpret type casting, the type unsafe strategy.

I'm aware it requires type casting. Hence it shouldn't be enabled by default.

But branded types are widely used. So an escape hatch is useful because they're gonna be used anyway. And having a built in way to do that increases Nestia's appeal.

I dont see what would be the harm in defining an object key in the config, which if an object has, and the object is a part of an intersection, makes the object get discarded from the intersection by Nestia. 

It's a completely opt in behavior and the user can be made aware of the risks if the key is mistyped or not unique.

**Comment by samchon** [comment]
Close by same reason with https://github.com/samchon/typia/issues/933.

I am not affordable to develop the feature, so give up this spec or do contribute please.

**Comment by MatAtBread** [comment]
If you stumbled across this issue, I have patched typia to support brands. See https://github.com/samchon/typia/issues/911#issuecomment-2515870176

**Comment by samchon** [comment]
> If you stumbled across this issue, I have patched typia to support brands. See [samchon/typia#911 (comment)](https://github.com/samchon/typia/issues/911#issuecomment-2515870176)

This problem must be solved by defining priority relationship when insensible intersection type case.

**Comment by bradleat** [comment]
@samchon  idk why you insist on fighting your community on this. you've created a great tool and @MatAtBread has a reasonable solution to everyone's problem. please adopt it.

**Comment by blaiseludvig** [comment]
There is an incredibly simple userland solution for this.
I'm not sure if it covers all cases, but it worked flawlessly for me for object validation.

You just have to unwrap the branded types before passing it to typia.

```ts
import { UnwrapTagged } from "type-fest";
import { Tag } from "type-fest/source/tagged";
import { Brand } from "effect";


// Recursively unwrap tagged types from all properties on an object
// Functions are ignored and excluded

// With type-fest's Tagged
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type UnwrapTaggedDeep<T> = T extends Tag<PropertyKey, any>
  ? UnwrapTaggedDeep<UnwrapTagged<T>>
  : T extends (infer U)[]
  ? UnwrapTaggedDeep<U>[]
  : T extends object
  ? {
      // eslint-disable-next-line @typescript-eslint/no-unsafe-function-type
      [K in keyof T as T[K] extends Function ? never : K]: UnwrapTaggedDeep<
        T[K]
      >;
    }
  : T;

// With Effect's Brand
export type UnbrandedDeep<T> = T extends Brand.Brand<string>
  ? UnbrandedDeep<Brand.Brand.Unbranded<T>>
  : T extends (infer U)[]
  ? UnbrandedDeep<U>[]
  : T extends object
  ? {
      // eslint-disable-next-line @typescript-eslint/no-unsafe-function-type
      [K in keyof T as T[K] extends Function ? never : K]: UnbrandedDeep<T[K]>;
    }
  : T;
```

And then use it like this:

```ts
if(typia.is<UnwrapTaggedDeep<MyTaggedObject>>(obj))
{
  return obj as MyTaggedObject;
}
if(typia.is<UnbrandedDeep<MyBrandedObject>>(obj))
{
  return obj as MyBrandedObject;
}
```
You can use assert the same way.

These rely on the unwrapper types `UnwrapTagged` and `Brand.Unbranded` provided by type-fest and Effect, but you can check their source code to make your own unwrapper if you don't have one yet.

Let me know if this solution is good enough for your use cases!
