### ISSUE TITLE
Feedback for “Setup”

### ISSUE THREAD

**Issue by jaenster** [samchon/nestia#1099]
At the bottom of the [setup page](https://nestia.io/docs/setup/), it is mentioned:

> [SWC](https://swc.rs/) author is preparing a new project [STC](https://github.com/dudykr/stc), and it does not erase type info.
> Therefore, nestia will support it.

However when i looked at the stc repository, and looked at the issues it is repeatably mentioned that this project is stale and not actively worked on. Maybe its wise to remove this comment at the setup page. To avoid people trying it out if the developer has mentioned it is not being worked on right now.

**Comment by samchon** [comment]
Would you send a PR about this issue?
