### ISSUE TITLE
Generate return `Invalid value used in weak set`

### ISSUE THREAD

**Issue by wibus-wee** [samchon/nestia#159]
## Bug Report

- [X] `npm install --save-dev nestia@next`

### Summary

I am a native speaker of Chinese, and my English maybe is terrible. Sorry.

  - **SDK Version**: 3.0.16-dev.20220930
  - **Expected behavior**: Generate successfully （成功生成）
  - **Actual behavior**: return `Invalid value used in weak set` （它返回了 `Invalid value used in weak set` 的报错）

When I run `npx nestia sdk`, it will return: （当我使用命令，`npx nestia sdk` 它会返回以下内容）

```bash
{ _: [ 'swagger' ] } # It comes from my project （这来自我项目的启动输出）
cwd:  /Users/***/core # too（这来自我项目的启动输出）
Invalid value used in weak set
```

### Code occuring the bug

```bash
git clone https://github.com/mogland/core.git
cd core
git checkout feat/nestia-sdk-generate
npx nestia sdk
```

**Comment by samchon** [comment]
I changed your `nestia.config.ts` file like below, and succeeded to running the `nestia`.

However, you're defining some types in the global definitnion like `global.isDev` and `global.consola`. My library `nestia` generates SDK library by parsing TypeScript source files, but it can't understand such non-standard implementation. If you remove such non-standard definitions, SDK would be well-generated.

**Comment by wibus-wee** [comment]
OK, Thanks!
