### ISSUE TITLE
Handling File Uploads

### ISSUE THREAD

**Issue by AtlasRW** [samchon/nestia#160]
Hi guys,
I'm only beginning with `nestia` and I'm facing probably some newbie questions that are linked together, but here they are :

- How can I define a different `content-type` for one endpoint ?
Because using `@Header` decorator doesn't seem to change the Swagger output by `nestia`

- Is it possible to handle File Uploads with Multer and `nestia swagger` / `nestia sdk` and how ?

**Comment by samchon** [comment]
Not support the file upload yet.

**Comment by samchon** [comment]
But it must be someday. I'm developing [typescript-json](https://github.com/samchon/typescript-json) and this feature would be after that project.

**Comment by AtlasRW** [comment]
Thanks for your response !

Is there currently a way to provide a custom content-type to `nestia`, at least ?

**Comment by samchon** [comment]
Nope, only application/json is supported

**Comment by DavidVaness** [comment]
@samchon Any progress / ideas in this regard? We just ran into this today

**Comment by samchon** [comment]
File uploading is related to frontend components. However, `@nestia/sdk` supports both NodeJS and Web browsers.

Considering such aspects, I don't have clear idea. If you have a good interface design about that, please write an issue suggesting it.
