### ISSUE TITLE
Schema Generated is Not Valid Swagger

### ISSUE THREAD

**Issue by bralax** [samchon/nestia#162]
### Summary
Nestia is currently generating schemas that contain invalid properties to be considered Swagger/OpenAPI. In particular, it includes a `JsDocTags` field on all properties which is invalid and should not be included. It also uses `patternProperties` to handle types of the form 
```
interface Map {
    [key: string]: any;
}
```

`patternProperties` is part of the Json-schema spec but is not a part of OpenAPI spec. Example of jsDocTags when they shouldn't be included within this repo: https://github.com/samchon/nestia/blob/master/demo/generic/swagger.json#L312

**Comment by samchon** [comment]
The JSON schema is generated by [typescript-json](https://github.com/samchon/typescript-json), another library of mine. I should remove those properties `jsDocTags` and `patternProperties`.

For reference, about the `jsDocTag`, I know that it is not a standard feature of JSON schema. However, I've defined such non-standard variable to help third party libraries like below case. For reference, the below example is a third party project which can automatically construct UI components only by TypeScript Type.

![image](https://user-images.githubusercontent.com/13158709/196005237-3a1fb2ff-cf03-4b46-80b1-845b6327bd28.png)

**Comment by bralax** [comment]
I think the concern here is that not all syntax in Json Schema is valid swagger so for example, the JsonSchema version of 
```
interface Map {
    [key: string]: string;
}

```
would be 
```
{
   "type": "object",
   "patternProperties": {
      "*": { "type": "string" }
    }
}
```
And the swagger would be:
```
```
{
   "type": "object",
   "additionalProperties": { "type": "string" }
}
```
You can't just inject json schemas of models into a swagger definition because of these subtle differences. There is a large overlap but as soon as you have to go outside of the overlap these differences break the ability to use the generated schemas elsewhere. Also Swagger is much stricter on extensions. If you want to add additional information that is not a property naturally declared on the schema, it must start with a prefix of `X-` to identify it as an extension.

**Comment by samchon** [comment]
Okay, I will update at v3.1.2 update. It may be done at Tuesday.
