### ISSUE TITLE
How can I name the schema in swagger document?

### ISSUE THREAD

**Issue by rojiwon0325** [samchon/nestia#176]
I made Request Body Interface by same way. one document schema has a interface name, but something has random name like "__type".

Why did it have a random name?

```typescript
  /**
   * 사용자 회원가입 API
   * @tag user
   * @tag public
   * @param body 사용자 계정 정보 전달
   * @returns 생성된 사용자의 세부 프로필 정보 응답
   * @throw 400 email duplicate
   */
  @Public()
  @Post()
  create(@helper.TypedBody() body: IUserUsecase.Create) {
    const { username, email, password } = body;
    return this.usecase.create({ username, email, password });
  }

  /**
   * 내 프로필 정보 수정 API
   * @tag user
   * @param body 변경할 정보만 포함
   * @returns 변경된 사용자 프로필 정보
   */
  @Patch('me')
  update(
    @AuthPublic() { id }: Auth.Public,
    @helper.TypedBody() body: IUserUsecase.Update,
  ) {
    const { username, bio, birth, phone } = body;
    return this.usecase.update({ id }, { username, bio, birth, phone });
  }
```
in swagger.json
```json
        "requestBody": {
          "description": "사용자 계정 정보 전달",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/__type.o1"
              }
            }
          },
          "required": true
        },

        "requestBody": {
          "description": "변경할 정보만 포함",
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/IUserUsecase.Update"
              }
            }
          },
          "required": true
        },
```

I defined interface here.
```typescript
export namespace IUserUsecase {
  export type FindOne = Pick<User.State, 'id'>;
  export type Create = Pick<User.State, 'email' | 'username' | 'password'>;
  export type Update = Partial<Pick<User.State, 'username'>> &
    Pick<User.MetadataVO, 'bio' | 'birth' | 'phone'>;
}

```

**Comment by samchon** [comment]
The `type` statement does not have its own name because it means an alias type in the compiler level.

Therefore, if you want to give their own name, use interface definitions like below:

```typescript
export namespace IUserUsecase {
    export interface FindOne extends Pick<User.State, "id"> {}
    export interface Create extends Pick<User.State, "email" | "username" | "password"> {}
    export interface Update extends Partial<...> {}
}
```

**Comment by samchon** [comment]
Found a way to support such type alias. It would be supported soon.

**Comment by samchon** [comment]
Update to `v3.1.5`, then it would be supported.

**Comment by rojiwon0325** [comment]
영어로 표현하기 어려워서 한글로라도 코맨트 남겨보겠습니다....
현재 저의 경우엔 namespace내에 타입이나 인터페이스를 정의합니다.

1. type 키워드를 사용하여 Pick등의 mapped Type을 사용하는 경우
3. 1번의 상황에서 & 연산까지 사용하는 경우
4. 인터페이스로 정의하는 경우 

```typescript
export namespace Userspace{
    export type UserType1 = Pick<User, 'id'>;
    export type UserType2 = Pick<User, 'id'> & Pick<User, 'name'>;

    export interface UserType3 extends Pick<User, 'id' | 'name'> {}
    export interface UserType4 {
        id: number;
        name: string;
    }
}
```

nestia는 현재 1번 상황과 인터페이스를 사용하는 경우(3,4번 경우)엔  **Userspace.UserType1** 와 같은 형태로 스키마명이 작성됩니다.
하지만 2번 같은 방식인 경우엔, **UserType2** 와 같은 방식으로 스키마명이 작성됩니다.
만약 namespace가 다르고 type명칭이 같은 경우엔, **UserType2.o1**, **UserType2.o2** 와 같은 방식으로 스키마명이 작성됩니다.

이는 일관성이 떨어진다는 생각이 들어서 namespace내에 속한 타입은 interface/type 방식과 상관없이 항상 namepsace 이름이 앞에 나오면 좋겠습니다.

그러면 위의 경우엔
 **Userspace.UserType1**
 **Userspace.UserType2**
 **Userspace.UserType3**
 **Userspace.UserType4** 와 같은 방식으로 스키마명이 작성될 것입니다. 
 이는 다른 namespace에 같은 이름의 타입이 존재해도 **Postspace.UserType1** 과 같이 명명 될 것입니다. 이 방식이 더 명확히 구분할 수 있고 일관성 있는 명명법이라고 생각합니다.
 
 nestia는 지금도 정말 멋지지만 한번 고려해주셨으면 합니다. 감사합니다.

**Comment by samchon** [comment]
Upgrade to `v3.1.6`, then your problem would be clear.

**Comment by rojiwon0325** [comment]
omg, amen...
