### ISSUE TITLE
Where are test code about @core.TypedParam() ?

### ISSUE THREAD

**Issue by rojiwon0325** [samchon/nestia#208]
can I read code about @core.TypedParam() ?
I want to refer to the test code about @core.TypedParam in order to write a test code for a @core.TypedQuery I made.

**Comment by rojiwon0325** [comment]
TypedQuery 함수를 짜봤는데, 테스트 코드를 어떻게 작성해야 할지 모르곘네요.

**Comment by samchon** [comment]
Here is the test code:

https://github.com/samchon/nestia/blob/master/packages/core/test/controllers/ConsumerSaleArticleCommentsController.ts#L28-L31

**Comment by samchon** [comment]
This is draft spec of the `TypedQuery`. Tell me your idea:

https://github.com/samchon/nestia/issues/209
