### ISSUE TITLE
New decorator `TypedQuery()`

### ISSUE THREAD

**Issue by samchon** [samchon/nestia#209]
Implement a new decorator `TypedQuery()`, which can take variables from request URL.

Also, `TypedQuery()` can have only atomic value types like below. No object or array type would be allowed.

```typescript
export interface IReferrer {
    id: string;
    fee: number;
    partner: boolean;
}
```

Some may have doubts about the query parameters. Looking at API of native [URLSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams), which can parse URL variables, only string typed property values are allowed. However, above interface `IReferrer` has `numeber `and `boolean` types. How it can be possible? Isn't it something wrong?

The answer is such `number` and `boolean` typed properties would be automatically casted, by analyzing the DTO structure in the compilation level, as other decorator functions like `TypedBody()` could.

```bash
export class BbsArticlesController {
    @TypedRoute.Patch(":section")
    public index(
        @TypedParam("section", "uuid") section: string,
        @TypedQuery() query: IReferrer,
        @TypedBody() input: IPage.IRequest
    ): IPage<IBbsArticle>;
}
```

**Comment by rojiwon0325** [comment]
1. same query key can multiple
ex) /path?a=1&a=2&a=3 -> a:number[]
2. query can boolean, string, number (another type is weired..)
3. query key can nullable

so I think
@TypedQuery(name:string, type:QueryType, option?:QueryOption)
```typescript
// QueryType -> same type TypedParam's second argument
interface QueryOption {
   multiple: boolean; // if true, query value is type[], default is false
   nullable: boolean; // if true, query value is nullable, default is false
} 
```

**Comment by samchon** [comment]
Then, allowing atomic array type seems more suitable:

```typescript
export interface IReferrer {
    id: string;
    fee: number[];
    partner: boolean;
}
```

Also, I won't make `TypedQuery()` below features:

```typescript
@TypedQuery("fee", "number") fee: number // do not allow
@TypedQuery() query: IRequestQuery // allow 
```

**Comment by 39-hn** [comment]
arrayformat of querystring can be various
[query-string#arrayformat](https://github.com/sindresorhus/query-string#arrayformat)
