### ISSUE TITLE
Suggestion: mime-type verification method

### ISSUE THREAD

**Issue by 39hn** [samchon/nestia#220]
### A description of the problem you're trying to solve.
Express has it's own method for checking mime-type (Request.is), but Nestia has implemented a duplicative method.

### An overview of the suggested solution.
1. using Express' Request.is
```ts
const request: express.Request = context.switchToHttp().getRequest();
if (!request.is("application/json")) {
    throw new BadRequestException(
        "Request body is not the application/json.",
    );
}
```

2. Or, Considering performance, using String.prototype.includes instead of current Split-Some method
```ts
const JSON_MIME_TYPE = "application/json";
const isApplicationJson = (text?: string) =>
    text === JSON_MIME_TYPE ||
    text !== undefined &&
    text.includes(JSON_MIME_TYPE);
```

[Benchmark between Split-Some and String.prototype.includes](https://perf.link/#eyJpZCI6InYwMGEyYTdkc3cyIiwidGl0bGUiOiJpc0FwcGxpY2F0aW9uSnNvbiIsImJlZm9yZSI6ImNvbnN0IGhlYWRlciA9IFwiYXBwbGljYXRpb24vanNvblwiO1xuY29uc3QgaGVhZGVyV2l0aFV0ZjggPSBcImFwcGxpY2F0aW9uL2pzb247IHV0Zi04XCI7XG5cbmNvbnN0IE1JTUVfVFlQRV9BUFBMSUNBVElPTl9KU09OID0gJ2FwcGxpY2F0aW9uL2pzb24nO1xuXG5jb25zdCBpc0FwcGxpY2F0aW9uSnNvbkJ5U3BsaXRTb21lID0gKHRleHQpID0%2BXG4gICAgdGV4dCAhPT0gdW5kZWZpbmVkICYmXG4gICAgdGV4dFxuICAgIC5zcGxpdChcIjtcIilcbiAgICAubWFwKChzdHIpID0%2BIHN0ci50cmltKCkpXG4gICAgLnNvbWUoKHN0cikgPT4gc3RyID09PSBNSU1FX1RZUEVfQVBQTElDQVRJT05fSlNPTik7XG5cbmNvbnN0IGlzQXBwbGljYXRpb25Kc29uQnlJbmNsdWRlcyA9ICh0ZXh0KSA9PlxuICAgIHRleHQgPT09IE1JTUVfVFlQRV9BUFBMSUNBVElPTl9KU09OIHx8XG4gICAgdGV4dCAhPT0gdW5kZWZpbmVkICYmXG4gICAgdGV4dC5pbmNsdWRlcyhNSU1FX1RZUEVfQVBQTElDQVRJT05fSlNPTik7XG5cbmNvbnN0IGlzQXBwbGljYXRpb25Kc29uQnlJZGVudGl0eU9wID0gKHRleHQpID0%2BXG4gICAgdGV4dCA9PT0gTUlNRV9UWVBFX0FQUExJQ0FUSU9OX0pTT047XG4gICIsInRlc3RzIjpbeyJuYW1lIjoiQ2hlY2sgaGVhZGVyIGJ5IElkZW50aXR5T3AiLCJjb2RlIjoiaXNBcHBsaWNhdGlvbkpzb25CeUlkZW50aXR5T3AoaGVhZGVyKTsiLCJydW5zIjpbMzIwNTAwMCwyOTE1MDAwLDIzMjEwMDAsMzg2NDAwMCwzODIwMDAsMjczNTAwMCw4NzkwMDAsMjMxMTAwMCw0Njk0MDAwLDQ0MDAwLDQ1OTQwMDAsMzA5MjAwMCw0MTI5MDAwLDEwMjkwMDAsNDQwMDAsMjUxNDAwMCw4MDUwMDAsMTgxMjAwMCw1MTQ3MDAwLDU2NTcwMDAsMjY0MTAwMCwxMTk2MDAwLDM3MzIwMDAsMjA0MTAwMCwyODA5MDAwLDE4MDIwMDAsMjczNjAwMCw0NDkxMDAwLDYwMDAwLDE4ODMwMDAsMTUxNzAwMCwxMDI0MDAwLDEwNDAwMCw0NTcwMDAsMTkzOTAwMCwyMTE0MDAwLDYyMDAwLDM4NDcwMDAsMzUxMzAwMCwzNzUxMDAwLDQ3MTMwMDAsNDQ2MDAwMCwzMzU5MDAwLDc3NTAwMCw0ODIxMDAwLDQ3MDkwMDAsNDk1NTAwMCwzNTMwMDAwLDMxNjYwMDAsMTUzNTAwMCw1MTA2MDAwLDIzNzcwMDAsMjA2NDAwMCw0MTY0MDAwLDM0NTYwMDAsMzQwOTAwMCwyMTY3MDAwLDMzNzEwMDAsNDQ1ODAwMCwzOTI3MDAwLDQ5MTkwMDAsMjA4NTAwMCw0ODEwMDAsNDMwNDAwMCw1MDc1MDAwLDI1NjEwMDAsOTY1MDAwLDI5NDYwMDAsNDUyMTAwMCw5NDEwMDAsMzIwMDAwLDQ2MzAwMCw0MjM3MDAwLDMzNjMwMDAsMzQxNTAwMCw1NjQ1MDAwLDI3NzEwMDAsNTIxMTAwMCw0NzE4MDAwLDQ2MzIwMDAsMzcyMDAwMCw1NTA3MDAwLDU2NTYwMDAsMzA1NzAwMCwzMTAwMCwyNDk2MDAwLDQ0MDcwMDAsMzg5NTAwMCwwLDIzMjIwMDAsNDgwMDAwMCwzMzgwMDAsMzE0MDAwLDQ0OTgwMDAsMTM0MjAwMCwxMzk1MDAwLDI5NDAwMDAsMzM2MjAwMCwyMDI5MDAwLDI4OTcwMDBdLCJvcHMiOjI4Mjk5MzB9LHsibmFtZSI6IkNoZWNrIGhlYWRlciBieSBTcGxpdFNvbWUiLCJjb2RlIjoiaXNBcHBsaWNhdGlvbkpzb25CeVNwbGl0U29tZShoZWFkZXIpOyIsInJ1bnMiOlsxMjc2MDAwLDkwMDAsMTA1NjAwMCw1MjYwMDAsMTI5MjAwMCw4NDEwMDAsMTAwMCw1NDgwMDAsMTI4MDAwMCw5MDAwLDEyODAwMDAsNDc1MDAwLDgxODAwMCwyNjcwMDAsNTYwMDAwLDEzNTMwMDAsMTgzMDAwLDEwMzgwMDAsMTM1MjAwMCw4OTkwMDAsMTM1MDAwLDgyMTAwMCwzMTMwMDAsNTUwMDAwLDU4MDAwMCwzODcwMDAsNzA2MDAwLDU4MTAwMCwzNzUwMDAsNzc0MDAwLDYwNTAwMCwzMjcwMDAsMTM1NjAwMCwxMjM5MDAwLDk0NDAwMCwxNDA3MDAwLDc0MDAwMCwxMDc3MDAwLDEwMTUwMDAsMTUxMDAwMCw0ODAwMDAsNDUyMDAwLDk4MjAwMCwxNTEyMDAwLDExODYwMDAsMTc3MDAwLDEyNjUwMDAsNTg1MDAwLDQ4NDAwMCw1MjEwMDAsMTIwNzAwMCw1MDAwMCwxMTYwMDAwLDExOTYwMDAsMTE2NTAwMCw1OTkwMDAsMTA0NTAwMCw0MDkwMDAsMTAwMCwxMzAyMDAwLDEyMzYwMDAsNTI3MDAwLDU2MDAwMCw1NDAwMDAsNDQ1MDAwLDc0MTAwMCw3MzAwMDAsNjk1MDAwLDEwMDAwLDIxNjAwMCw4OTEwMDAsMTAwMCw3OTcwMDAsMTA2MDAwMCwzMjQwMDAsOTY2MDAwLDEzODQwMDAsMjIyMDAwLDkxNzAwMCwxMTYzMDAwLDEyMzQwMDAsMTQ0OTAwMCwyNTgwMDAsNjIwMDAwLDEwMDAsNjM2MDAwLDkyMjAwMCwxNDQyMDAwLDI3NDAwMCwxMDY5MDAwLDEwMDAwLDk1ODAwMCw4OTIwMDAsMzEyMDAwLDEwMjAwMCw3MzkwMDAsNDUwMDAsNjU1MDAwLDg4NTAwMCwxMjc3MDAwXSwib3BzIjo3MzQ4ODB9LHsibmFtZSI6IkNoZWNrIGhlYWRlcldpdGhVdGY4IGJ5IFNwbGl0U29tZSIsImNvZGUiOiJpc0FwcGxpY2F0aW9uSnNvbkJ5U3BsaXRTb21lKGhlYWRlcldpdGhVdGY4KTsiLCJydW5zIjpbMjUwMDAsNjkyMDAwLDU1MDAwMCw4NzMwMDAsODgwMDAsNzM3MDAwLDUwMzAwMCwxMTcwMDAsMTA1NDAwMCw2NzcwMDAsNTcyMDAwLDUxMjAwMCw0NTEwMDAsNjIwMDAsNjAyMDAwLDEwMDUwMDAsMTA1MzAwMCwxMDAwMCw2NTYwMDAsMjc4MDAwLDEwMDEwMDAsMjYyMDAwLDEwNDYwMDAsOTkzMDAwLDEwMDAsMTExNjAwMCwxMDExMDAwLDQwMzAwMCwxNDUwMDAsNjY2MDAwLDEyMzQwMDAsMTE3MzAwMCw1MDAwLDQ1MTAwMCw2MDYwMDAsOTMzMDAwLDQ0NjAwMCwxMDAwLDEwODYwMDAsOTQ0MDAwLDExMzUwMDAsNDUyMDAwLDk1MjAwMCwxMzkwMDAsNTkzMDAwLDQwNzAwMCwxMDQxMDAwLDE4MzAwMCw2MjAwMCw5MTQwMDAsOTg4MDAwLDU0NDAwMCwxMDgwMDAwLDExMTQwMDAsMTI0MDAwMCw5OTIwMDAsMzE5MDAwLDEwNzkwMDAsMTE1NTAwMCw5ODkwMDAsNzUyMDAwLDQ3NzAwMCwxMzEwMDAsODgwMDAsMTE1NjAwMCwyMjcwMDAsODcwMDAwLDEwMDAsODA5MDAwLDc1MjAwMCw0NzkwMDAsODY0MDAwLDcwMDAwMCw2MDIwMDAsNjkyMDAwLDkwODAwMCw0MzUwMDAsNjQyMDAwLDExMTcwMDAsMTA3NjAwMCw5MDMwMDAsNjAyMDAwLDYwMjAwMCw5MDAwMCwxMjM0MDAwLDY4MTAwMCwzMzgwMDAsMTE5ODAwMCw3MDAwLDIwMDAsNjkyMDAwLDExNzAwMDAsNzY4MDAwLDQ1MTAwMCw2MDIwMDAsMjQxMDAwLDU0NDAwMCwxODAwMDAsNDgyMDAwLDcwMjAwMF0sIm9wcyI6NjM2ODUwfSx7Im5hbWUiOiJDaGVjayBoZWFkZXIgYnkgSW5jdWRlcyIsImNvZGUiOiJpc0FwcGxpY2F0aW9uSnNvbkJ5SW5jbHVkZXMoaGVhZGVyKTsiLCJydW5zIjpbMzAzOTAwMCwzMjE4MDAwLDEzMTIwMDAsMzUxMjAwMCw0MTAwMDAwLDMwMzEwMDAsNTE2MDAwLDExMzkwMDAsMjI3MzAwMCwxNzgyMDAwLDQxODAwMDAsMTQzNjAwMCwzMDYwMDAwLDU1NjAwMCwzNDkzMDAwLDgzNDAwMCw0MDQ0MDAwLDQxOTgwMDAsMzkwMjAwMCwxMzQxMDAwLDE3NjcwMDAsNDM4NjAwMCw1MzUxMDAwLDEwMjEwMDAsODAxMDAwLDM3MjYwMDAsMTk1MDAwLDI0MTAwMDAsMTE4MDAwLDE2MDAwLDQ4NTYwMDAsMjY5NTAwMCwyODEwMDAsNDA2MDAwLDE0MjkwMDAsNDI5MDAwLDMzODAwMCw1MDYxMDAwLDEwMjEwMDAsMTE3NDAwMCw0NDQwMDAwLDQ0MTIwMDAsODYxMDAwLDMwNDEwMDAsMTAxMjAwMCwxNzA0MDAwLDI0NzEwMDAsMTYyMDAwMCwxNTM0MDAwLDE0MjYwMDAsMjk3MDAwMCwxODAwMDAwLDMwNjkwMDAsNDQzNDAwMCwzNTgzMDAwLDUxMTcwMDAsNDk2NTAwMCw3MDcwMDAsNDA5MDAwMCwxODM4MDAwLDQ2OTAwMCwyMTUzMDAwLDIwMDAwLDkxNDAwMCw0NTMzMDAwLDEzNTgwMDAsNDk5MTAwMCw0NzQ0MDAwLDEyNjEwMDAsMjE5MDAwLDE0MzIwMDAsMTQ1OTAwMCwyMjYwMDAsMTMyMDAwMCw0ODEzMDAwLDQ2OTkwMDAsMzY5NDAwMCwzNjMxMDAwLDEzNzIwMDAsMTA1MjAwMCwzNzY1MDAwLDM4MzcwMDAsNDIzMjAwMCwyMjEyMDAwLDM3NzAwMDAsMjcyNjAwMCwxNDgwMDAsMTY5MjAwMCwzOTY0MDAwLDIwMjEwMDAsMjIwMDAwMCwxNjcyMDAwLDUzNDAwMCwxNTc4MDAwLDI0MzQwMDAsNDM2NTAwMCwxMDAwLDM4OTUwMDAsMTkzMzAwMCw0ODk5MDAwXSwib3BzIjoyMzk3NzkwfSx7Im5hbWUiOiJDaGVjayBoZWFkZXJXaXRoVXRmOCBieSBJbmN1ZGVzIiwiY29kZSI6ImlzQXBwbGljYXRpb25Kc29uQnlJbmNsdWRlcyhoZWFkZXJXaXRoVXRmOCk7IiwicnVucyI6WzEzNTgwMDAsMTEzMDAwLDQ1NTAwMCwxNTI1MDAwLDEwNjIwMDAsODg2MDAwLDMwNTAwMDAsNzAyMDAwLDE0MjgwMDAsMTM3NjAwMCwxNzQzMDAwLDMwNDEwMDAsMjcyNDAwMCwyMTg3MDAwLDMyNDQwMDAsMzg4MDAwLDE4MDMwMDAsMjQ3MzAwMCwyMjYwMDAsMjE5MTAwMCwyNjI0MDAwLDIxOTEwMDAsMjQxNDAwMCwxNTc4MDAwLDI1ODAwMDAsMTYxOTAwMCwzMDEzMDAwLDI5NDAwMCwxNDA2MDAwLDMwNzQwMDAsNTE4MDAwLDMyMjQwMDAsMjE1NTAwMCwxMTA2MDAwLDI5MjgwMDAsMTQxMDAwLDExOTAwMCwxMjcwMDAwLDMwNTIwMDAsMTExNTAwMCwyMzYwMDAsMTAwMCwxMTA1MDAwLDEzMTUwMDAsMjcxMjAwMCwxMzk5MDAwLDEwNjYwMDAsMzI1NzAwMCwxMTEzMDAwLDg1NjAwMCwxMjQ0MDAwLDI0MjAwMDAsMTAwMCwyMzQ5MDAwLDE5MzIwMDAsODcyMDAwLDMxOTgwMDAsMzk5MDAwLDk1ODAwMCwyNDExMDAwLDExMjgwMDAsMjE5MTAwMCwzMDgwMDAsMjYwMDAwLDU2MzAwMCwyOTgwMDAwLDM4NDAwMCwyOTg3MDAwLDMxMzAwMCwxMDcwMDAsMjE5MTAwMCwxMDMwMDAwLDIxNTAwMCw5MzAwMDAsMTQ3NTAwMCwxNzY1MDAwLDIxOTEwMDAsMzE0NzAwMCw4NTYwMDAsMjA0MDAwMCw0MTIwMDAsMjIzMzAwMCwyNjk5MDAwLDM0MzgwMDAsMjE5MTAwMCwyNTU0MDAwLDI4NTQwMDAsMzcxMjAwMCwxMjE3MDAwLDkwMDAwLDE0NzUwMDAsMTE3MDAwMCwzNDEwMDAsNDcwMDAwLDE0MjkwMDAsMjQyODAwMCwxMDAwLDI0ODUwMDAsMTM2NDAwMCwyNDk3MDAwXSwib3BzIjoxNTkzNjEwfV0sInVwZGF0ZWQiOiIyMDIzLTAxLTE4VDA0OjE4OjI0LjAyOFoifQ%3D%3D)

**Comment by samchon** [comment]
What about sending a PR about this?

**Comment by 39hn** [comment]
not sure which one to use 😖

**Comment by 39hn** [comment]
I made benchmark of mime-type verification.

[https://github.com/39hn/mime-type-check-benchmark](https://github.com/39hn/mime-type-check-benchmark)

```
IdentityOperator#JSON_HEADER x 853,628,240 ops/sec ±0.91% (90 runs sampled)
IdentityOperator#JSON_HEADER_WITH_CHARSET: failed
IdentityOperator#PLAIN_HEADER x 859,293,207 ops/sec ±1.18% (88 runs sampled)
IdentityOperator#PLAIN_HEADER_WITH_CHARSET x 839,442,760 ops/sec ±1.29% (89 runs sampled)
IdentityOperator#EMPTY_HEADER x 832,590,602 ops/sec ±1.21% (88 runs sampled)
IdentityOperator#UNDEFINED_HEADER x 90,767,291 ops/sec ±0.76% (88 runs sampled)
TypeIs#JSON_HEADER x 984,103 ops/sec ±0.67% (88 runs sampled)
TypeIs#JSON_HEADER_WITH_CHARSET x 697,578 ops/sec ±1.95% (84 runs sampled)
TypeIs#PLAIN_HEADER x 1,118,033 ops/sec ±1.15% (90 runs sampled)
TypeIs#PLAIN_HEADER_WITH_CHARSET x 881,569 ops/sec ±0.65% (91 runs sampled)
TypeIs#EMPTY_HEADER x 98,558,744 ops/sec ±0.53% (89 runs sampled)
TypeIs#UNDEFINED_HEADER x 157,255,478 ops/sec ±2.12% (85 runs sampled)
SplitSome#JSON_HEADER x 6,021,528 ops/sec ±1.40% (88 runs sampled)
SplitSome#JSON_HEADER_WITH_CHARSET x 4,961,624 ops/sec ±2.64% (82 runs sampled)
SplitSome#PLAIN_HEADER x 5,786,325 ops/sec ±2.72% (81 runs sampled)
SplitSome#PLAIN_HEADER_WITH_CHARSET x 5,400,885 ops/sec ±0.56% (91 runs sampled)
SplitSome#EMPTY_HEADER x 6,493,469 ops/sec ±0.73% (88 runs sampled)
SplitSome#UNDEFINED_HEADER x 169,434,666 ops/sec ±0.57% (89 runs sampled)
StringIncludes#JSON_HEADER x 763,834,722 ops/sec ±1.45% (82 runs sampled)
StringIncludes#JSON_HEADER_WITH_CHARSET x 31,277,279 ops/sec ±0.72% (89 runs sampled)
StringIncludes#PLAIN_HEADER x 142,697,977 ops/sec ±0.70% (90 runs sampled)
StringIncludes#PLAIN_HEADER_WITH_CHARSET x 40,414,301 ops/sec ±0.50% (87 runs sampled)
StringIncludes#EMPTY_HEADER x 140,906,467 ops/sec ±0.48% (88 runs sampled)
StringIncludes#UNDEFINED_HEADER x 85,844,623 ops/sec ±0.57% (91 runs sampled)
```

`TypeIs` is what Express' `req.is` use.

gonna make PR with String.prototype.includes :D
