### ISSUE TITLE
Cannot find type in *.d.ts file (TS2304)

### ISSUE THREAD

**Issue by rojiwon0325** [samchon/nestia#230]
If a controller class depend on *.d.ts file(or something that depend on *.d.ts file), I can't command "nestia sdk" or "nestia swagger".

If i command that, throw Error.

example. IEnv is defined in env.d.ts file. so i don't have line "import ~~".
<img width="639" alt="스크린샷 2023-01-26 오전 1 52 09" src="https://user-images.githubusercontent.com/68629004/214626924-c9af657b-f68e-4745-b438-f4adfb75128c.png">

**Comment by samchon** [comment]
Can you uploas an example project file?

**Comment by rojiwon0325** [comment]
https://github.com/industriously/account-server/tree/oauth

컨트롤러 위치: https://github.com/industriously/account-server/blob/oauth/src/api/account/presentation/sign-in.controller.ts

가드 위치: https://github.com/industriously/account-server/blob/oauth/src/api/account/guard/google/index.ts

실제 IEnv와 의존성을 갖는 strategy 위치: https://github.com/industriously/account-server/blob/oauth/src/api/account/guard/google/google.strategy.ts

**Comment by samchon** [comment]
Oh my god, you are configuring NodeJS global type directly.

In that case, you have to reference the declaration file like below:

```typescript
/// <reference path="../../../../infrastructure/config/env.d.ts" />

import { PROFILEKEY } from '@COMMON/constant';
import { HttpExceptionMessage } from '@COMMON/exception';
import { Google, StrategyException } from '@devts/nestjs-auth';
import { IProfile } from '@INTERFACE/common';
import { Injectable, HttpException, HttpStatus } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import typia from 'typia';

@Injectable()
export class GoogleStrategy extends Google.AbstractStrategy<
  PROFILEKEY,
  'email' | 'profile',
  IProfile
> {
  constructor(config: ConfigService<IEnv, true>) {
    super({
      key: 'profile',
      client_id: config.get('GOOGLE_CLIENT_ID'),
      client_secret: config.get('GOOGLE_CLIENT_SECRET'),
      redirect_uri: config.get('GOOGLE_OAUTH_CALLBACK'),
      access_type: 'offline',
      prompt: 'select_account',
      scope: ['email', 'profile'],
    });
  }
  protected throw({ statusCode, message }: StrategyException): never {
    throw new HttpException(
      message ?? HttpExceptionMessage.UAE,
      statusCode ?? HttpStatus.UNAUTHORIZED,
    );
  }
  validate(identity: Google.IdToken<'email' | 'profile'>): boolean {
    typia.assert(identity);
    return true;
  }
  transform(identity: Google.IdToken<'email' | 'profile'>): IProfile {
    const { name: username, email, sub } = identity;
    return { username, email, sub, oauth_type: 'google' };
  }
}
```

**Comment by industriously** [comment]
oh my god..thank you...

**Comment by rojiwon0325** [comment]
thank you..

**Comment by sergio-milu** [comment]
> ```ts
> /// <reference path="../../../../infrastructure/config/env.d.ts" />
> ```

why do we need this? I think I'm facing a similar issue

I have some utility types in a `@types/utils.d.ts` files that looks like this

```
  type RemoveIndex<T> = {
    [K in keyof T as string extends K
      ? never
      : number extends K
      ? never
      : K]: T[K];
  };

  declare type KnownKeys<T> = keyof RemoveIndex<T>;
