### ISSUE TITLE
Why not re-export `@nestia/fetcher` types to avoid requiring the user to add it as a dependency?

### ISSUE THREAD

**Issue by TheYarin** [samchon/nestia#244]
## Question

The `@nestia/fetcher` package's README mentions:
> if you're a client developer who've installed an SDK library which has been generated by the [@nestia/sdk](https://github.com/samchon/nestia), you also need to install this @nestia/fetcher module. With the IConnection and HttpError instances provided by this @nestia/fetcher, you can enjoy the SDK library much conveniently.

Why not just re-export the needed types (`IConnection`, `HttpError`, etc.) in the generated SDK code to avoid requiring the user to add it as a dependency?

And another question, why doesn't the SDK code generation just generate a basic `package.json`? Or maybe it does? It's not clear from the docs.

**Comment by samchon** [comment]
If a frontend project imports multiple SDK libraries, then it is not possible to catch `HttpException` error by duplication.

I'm newly making documents in the new domain https://nestia.io

Thanks for your suggestion.
