### ISSUE TITLE
Do you have another way to implement DTO?

### ISSUE THREAD

**Issue by pvhuy84** [samchon/nestia#250]
I think using comments for logic code is not a good idea.
So, Do you have another way to implement a validated data request body?

**Comment by samchon** [comment]
No way in `@nestia/core` which is using `typia`.

If you need additional type checking, just make a new function doing that.

**Comment by pvhuy84** [comment]
Got it, thank you.

**Comment by samchon** [comment]
Only way supporting custom function is just using parameter, but I can't sure it may effective

```typescript
@TypedBody((input: YourDto) => YourValidationLogic...)
```
