### ISSUE TITLE
Reason for Encrypted Routes? 

### ISSUE THREAD

**Issue by Aderinom** [samchon/nestia#253]
## Question
I would like to understand the benefit of Encrypted Routes. 
I'd assume that any production rest api will be served over https directly.
So is there any reason to add an extra layer of encryption on top of that or is this more for the edgecase the api is served over normal http?

**Comment by samchon** [comment]
It is just to block debugging from google chrome by clicking F12.

Also, there's no special reason why. Just Korean government forces financial developers to encrypt once more.
