### ISSUE TITLE
SDK generate incorect

### ISSUE THREAD

**Issue by pvhuy84** [samchon/nestia#255]
I think for output of api should be `export type Output = Primitive<Model>;` instead of `export type Output = Model;`

**Comment by samchon** [comment]
Configure `nestia.config.ts` file to have `primitive: false` property.

```typescript
import sdk from "@nestia/sdk";

export const NESTIA_CONFIG: sdk.INestiaConfig = {
    input: "src/controllers",
    output: "src/api",
    primitive: false,
    swagger: {
        output: "dist/swagger.json",
    },
};
export default NESTIA_CONFIG;
```

https://github.com/samchon/nestia/blob/b93be57477e52ef6cc6e4c6625a937bd993374d6/packages/sdk/src/INestiaConfig.ts#L69-L82

**Comment by pvhuy84** [comment]
Hi @samchon, I try use sdk with react from CRA (monorepos). But I got an error like this:

```
Module parse failed: Unexpected token (10:12)
File was processed with these loaders:
 * ../../node_modules/@pmmmwh/react-refresh-webpack-plugin/loader/index.js
 * ../../node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
| //================================================================
| import { Fetcher, Primitive } from '@nestia/fetcher';
> import type { IConnection } from '@nestia/fetcher';
```
Do you have document for using SDK with a FE framework?

**Comment by samchon** [comment]
Install `@nestia/fetcher` on SDK

https://github.com/samchon/nestia/wiki/SDK-Generator#distribution

**Comment by pvhuy84** [comment]
It's still not working, I tried to install both the backend and frontend code.

**Comment by samchon** [comment]
Oops, I misunderstood your error message.

Can you provide me an example project about that bug?

**Comment by pvhuy84** [comment]
@samchon I pushed here: https://github.com/pvhuy84/nestia-test

**Comment by samchon** [comment]
Your DTO types are separated into multiple directories. It is the reason why import statements became such long.

If you consider distributing SDK library, I recommend you to gather DTO types into SDK directory.

Below is an example structure for SDK distribution

  - `src`
    - `api`
      - `dto`: Gather DTO types into here
      - `functional`: SDK would be generated into here

**Comment by pvhuy84** [comment]
you mean, I cannot use a structure module like NestJS when I use this SDK for frontend?

**Comment by samchon** [comment]
Considering distribution of SDK with DTO, my answer is "No, you can't".

If separate DTO types into multiple directories following NestJS guide, you have to publish entire server code.

**Comment by pvhuy84** [comment]
Got it, thanks for your response!
