### ISSUE TITLE
How to write summary of API in Swagger?

### ISSUE THREAD

**Issue by kakasoo** [samchon/nestia#256]
**In English.**

Hello. First of all, thank you for this amazing library.

I'm going to fill out the Swagger document and hand it over to the front developer. However, since there is no way to display a summary on each API of the swagger document, there is a problem that you have to infer by looking at the resource name of the API and the path written in RESTful.
If the first line of the top comment of the controller method is recognized as a summary, I think I can understand the document faster.

```typescript
/**
 * it's very important API -> it will be summary of API document.
 *
 * if you want to use... -> description of API document.
 *
 * @param id
 * @returns true, just return true. that's all.
 */
@TypedRoute.Post(':id')
async nestiaTest(@TypedParam('id', 'number') id: number) {
  return true;
}
```

**In Korean.**

안녕하세요. 우선 이런 좋은 라이브러리를 만들어주신 데에 감사드립니다.

저는 현재 스웨거 문서를 작성하여 프론트 개발자에게 넘기려고 합니다. 다만 swagger 문서의 각 API 상에서 summary를 표시할 방법이 없다 보니 API의 리소스 이름과 RESTful하게 작성되어 있는 경로를 보고 유추해야 하는 문제가 있습니다.
만약 controller method의 상단 주석 첫 줄을 summary로 인식하게 해준다면 더 빠르게 문서를 이해할 수 있을 거라고 생각합니다.

```typescript
/**
 * it's very important API -> it will be summary of API document.
 *
 * if you want to use... -> description of API document.
 *
 * @param id
 * @returns true, just return true. that's all.
 */
@TypedRoute.Post(':id')
async nestiaTest(@TypedParam('id', 'number') id: number) {
  return true;
}
```

**Comment by samchon** [comment]
Update to `@nestia/sdk@1.0.14`, then it works.

**Comment by kakasoo** [comment]
Cool! I can't wait to see this right now! Thank you!

**Comment by kakasoo** [comment]
In my project, the summary is partially applied. I can't predict under what circumstances this is created in. I tried to create a virtual project and show you this situation instead of showing the code of my actual project, but I can't reproduce this situation. Summary is not visible in all APIs.
However, what I thought was a summary sometimes appears in the description with a new line.

In Korean
제 프로젝트에서 현재 summary가 부분적으로만 나타납니다. 어떻게 작성해야만 이게 생성되는지 예측이 안되네요. 일단 제 프로젝트 코드를 보여주는 것 대신 임의의 프로젝트를 만들어서 코드를 보여주려고 했는데, 여기서는 같은 상황이 재현되질 않습니다. summary가 모든 API에서 안나타나고 있습니다.
다만 제가 summary를 의도한 게 줄바꿈 문자를 포함하여 설명에서 나오는 경우가 있습니다.

```bash
git clone https://github.com/kakasoo/nestia-demo
cd nestia-demo
git switch nestia#256-2
npm i
npx nestia swagger
npm run start:dev
```

<img width="1281" alt="image" src="https://user-images.githubusercontent.com/55487286/224496338-0f9ffd54-56f1-4275-b61f-f5937c283987.png">

**Comment by samchon** [comment]
Use `.` symbol before new line.

**Comment by kakasoo** [comment]
OK, thanks! I'll do it right away.
