### ISSUE TITLE
How can I use it when dto package have been separated using yarn workspace?

### ISSUE THREAD

**Issue by Lee-KyungSeok** [samchon/nestia#259]
Thank you for making very convenient library. 
I frequently separate dto and api packages. But when i generated sdk, i could not sharing this sdk with other engineer due to the format of the import that used dist.

```
import type { CreateUser } from "./../../../../../../contract/dist/users/commands/CreateUser";
import type { UserView } from "./../../../../../../contract/dist/users/views/UserView";
```

Would you explain how to change this import format? Thank you.

This is sample codes. (Branch nestia)

https://github.com/Lee-KyungSeok/Blog-Dto-Sharing-Sample/blob/nestia/packages/api/lib/api/functional/api/users/index.ts

**Comment by samchon** [comment]
I recommend not separate and gather DTO into SDK.

I don't know how to distinguish monorepo in compiler level, therefore, it is hard to response your case at now.

**Comment by Lee-KyungSeok** [comment]
So sad to hear that. 
I had to split packages to share dto pacakage with frontend, so it will take some time to migrate our main api server. 😂😂😂
But I will use this library to  generate swagger automatically and use typia !!

Thank you for answering my question

**Comment by samchon** [comment]
Any special reason separating DTO module?

**Comment by Lee-KyungSeok** [comment]
um..
The main reason was that i needed to share dto with frontend before knew about this library.  hahaha..
We had to to deploy dto as npm packages independently from the api server because we did not to want share api codes.

The second reason was that our business logic separated into packages and share with sometimes shared with another repo(mono repo). But that controller dto was often same with service dto. 

I recently listened to your session (nestjs korea) and thought that changes the way of sharing dto to make collaboration more easier.

Thank you.~

**Comment by samchon** [comment]
I will study how to construct import statement like you.

It may possible until last week of April.

**Comment by Lee-KyungSeok** [comment]
Oh Thank you! i will wait for it.

**Comment by samchon** [comment]
Before waiting for until last week of April, will you try below way? It would works.

1. Publish DTO npm module, instead of using through alias paths
2. Import the DTO module in backend project
3. Build SDK library

**Comment by samchon** [comment]
Your problem can be solved just by configuring `tsconfig.json` file to adding `include` property.
