### ISSUE TITLE
Optional query is assigned "undefined" string

### ISSUE THREAD

**Issue by industriously** [samchon/nestia#268]
findMany api has a optional query 'page'.
but if page is undefined, url is written as "/products?page=undefined". and this query value is string "undefined".

i think, "/products?" or "/products" is right.
(so i think, undefined type should be handled separately.)

In Korea,
 
findMany api를 구현했습니다. page는 optional한 쿼리입니다. sdk를 통해 findMany(connection)를 실행하면 undefined가 문자열 "undefined"로 전달되는 버그가 있습니다. ( ex) "/products?page=undefined" )
 이는 URLSearchParams의 처리 방식 때문인 것 같습니다. 제 생각에는 undefined값은 키조차 UrlSearchParams 객체 생성 인자로 전달되지 않아야 할 것 같습니다. ( ex) "/products?", "/products" )

```typescript
// This is nestia sdk.
export namespace findMany
{
    export type Output = PaginatedResponse<ProductSchema.General>;

    export const METHOD = "GET" as const;
    export const PATH: string = "/products";
    export const ENCRYPTED: Fetcher.IEncrypted = {
        request: false,
        response: false,
    };

    export function path(page: number | undefined): string
    {
        return `/products?${new URLSearchParams(
        {
            page
        } as any).toString()}`;
    }
}
```

**Comment by samchon** [comment]
Upgrade to `@nestia/sdk@1.0.11`, then would be fixed.

**Comment by industriously** [comment]
now @nestia/sdk 1.0.12, sdk path function logic is changed, but same bug still happens.

**Comment by samchon** [comment]
@industriously Show me your code.

**Comment by samchon** [comment]
Thanks for detailed reporting.

I haven't known about the `URLSearchParams`, as I've not used query parameters at all.

Now, update to `@nestia/sdk@1.0.13`, then everything would be fine.
