### ISSUE TITLE
NestJS project generator from `swagger.json` file

### ISSUE THREAD

**Issue by samchon** [samchon/nestia#292]
There're some people that want to migrate their backend project from another language to NestJS.

To support those people, I think that NestJS project generator from `swagger.json` file would be the best choice.

Therefore, develop the generator, that would have `@nestia/migrate` package name.

**Comment by afilp** [comment]
At what stage is this currently? This feature would be great for migrations and we may like to use it. Thanks!

**Comment by samchon** [comment]
@afilp Starts from next week, and may require a month.

**Comment by kakasoo** [comment]
I have to proceed with the spring project which is written as java/kotlin soon. If I use the technology covered by this issue, is it possible to deal with the test code of this project separately as TypeScript code?
I am very interested in using this.

**Comment by samchon** [comment]
Maybe published on Sunday or next week's Monday.

Most be done, but would support only openapi 3.0 spec at first.
