### ISSUE TITLE
when I use union type, import path and namespace for Output type is lost in sdk.

### ISSUE THREAD

**Issue by industriously** [samchon/nestia#296]
I often use generic, union, and layer form(by namespace) when writing type.

If i use mix union type and the other, Output type in sdk not be correctly.

**bug: import path and namespace is lost.**

```typescript
@Get('case 1')
test(): Promise<number | string | IUser> {
     throw Error();
  }
// in sdk
export type Output = string | number | IUser;
// the import path for the "IUser" type is lost.

@Get('case 2')
test(): Promise<TryCatch<IUser | string, IFailure>> {
     throw Error();
  }
// in sdk
export type Output = TryCatch<string | IUser, IFailure<IFailure.Type, string>>;
// the import path for the "IUser" type is lost. -> union
// TryCatch, IFailure path is not lost. -> not union

@Get('case 3')
test(): Promise<TryCatch<IUser, IFailure.Business.Invalid | IFailure.Business.Fail>> {
     throw Error();
  }
// in sdk
 export type Output = TryCatch<IUser, Invalid | Fail>;
// the namespace of Invalid, Fail is lost.
// the import path for "Invalid" and "Fail" is lost
// +) Of course, the import path for namespace "IFailure" was also not added.

@Get('case 4 -> everything is ok')
test(): Promise<TryCatch<IUser, IFailure.Business.Invalid>> {
     throw Error();
  }
// in sdk
export type Output = TryCatch<IUser, IFailure.Business.Invalid>;
// everything is ok.
```

결론적으로 제가 발견한 버그 현상은 유니온을 섞었을 때, namespace가 생략되고 import 경로가 유실되는 것입니다.

**Comment by samchon** [comment]
Your example code is insufficient.

Link or upload your project.

**Comment by industriously** [comment]
복잡한 타입을 정의한 상황에서 정확히 유니온이 사용된 부분에서만 import가 유실되고 namespace가 생략됩니다.

예를 들어
```typescript
 Promise<TryCatch<
      IAuthentication.Credentials,
      IFailure.Business.Invalid | IFailure.Business.Fail
    >>
```
에서도 IAuthentication.Credentials는 정상적으로 생성되고, Invalid, Fail만 문제가 발생합니다.

**Comment by industriously** [comment]
> Your example code is insufficient.
> 
> Link or upload your project.

ok! wait a minute.

**Comment by industriously** [comment]
root
https://github.com/industriously/ne-commerce/tree/refactoring

branch: refactoring

controller path
[// target: auth.controller.ts, user.controller.ts, users.controller.ts](https://github.com/industriously/ne-commerce/tree/refactoring/src/api/controller)

sdk path
https://github.com/industriously/ne-commerce/tree/refactoring/src/sdk

exception interface path
https://github.com/industriously/ne-commerce/blob/refactoring/src/sdk/interface/common/exception.interface.ts

**Comment by samchon** [comment]
It is possible to fix this bug, however, the solution requires to prohibit unnamed type like your another issue #293.

Considering those issues, I think that exact generic type analyzing is much important.

Therefore, I decided to prohibit the unnamed type and make this issue be possible.

Upgrade `@nestia/sdk@1.0.19`, then this bug would be fixed.
