### ISSUE TITLE
Handling numbers that overflow Typescript "number" type

### ISSUE THREAD

**Issue by theInfiniteWill** [samchon/nestia#298]
## How are JSON values larger than Number.MAX_VALUE handled?
Will the number be converted to string or will the value be an incorrect?

Is there an option to modify the behaviour so that the library can handle numbers larger than Number.MAX_VALUE?

**Comment by samchon** [comment]
Become type error -> `typia.TypeGuardError`

https://github.com/samchon/typia/blob/master/src/TypeGuardError.ts
