### ISSUE TITLE
Error when no parameter exists

### ISSUE THREAD

**Issue by samchon** [samchon/nestia#3]
When declaring a controller method that has not any parameter, it becomes an error.

```typescript
import * as helper from "encrypted-nestjs";
import * as nest from "@nestjs/common";

@nest.Controller("bbs/articles")
export class BbsArticleController
{
    @helper.EncryptedRoute.Get()
    public async index(): Promise<IPage<IBbsArticle.ISummary>>;
}
```

**Comment by PrimeDominus** [comment]
I've looked at https://github.com/samchon/encrypted-nestjs and I'm wondering why not just use the documented method for encryption coded into Nestia directly? https://docs.nestjs.com/security/encryption-and-hashing

I'm relatively new to NestJS, though I'm guessing Nestia would be more widely used if it doesn't have custom dependencies that give the impression they may not be maintained in the future.

**Comment by PrimeDominus** [comment]
Furthermore, another custom library https://www.npmjs.com/package/encrypted-fetcher is used as a further dependency, which in turn uses node-fetch. Why not code all this directly into Nestia using the official way? https://docs.nestjs.com/techniques/http-module

**Comment by samchon** [comment]
The example code you've pasted in (https://docs.nestjs.com/security/encryption-and-hashing) is just to explain how to encrypt and decrypt data. Therefore, encryption decorators like `EncryptedRoute.Post()` in the `encrypted-nestjs` is not natively supported by the **NestJS**.

https://github.com/samchon/encrypted-fetcher/blob/master/src/AesPkcs5.ts

Also, the way to encrypt & decrypt data in the `encrypted-fetcher` is not ultimately different with the explanation what you've pasted in.

**Comment by samchon** [comment]
And you told that using `axios` is the official way, however, I've different aspect about that. I think that [`fetch`](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) is much official feature within framework of the standard.
