### ISSUE TITLE
Feature Request: TypedQuery support array type

### ISSUE THREAD

**Issue by industriously** [samchon/nestia#302]
TypedQuery가 object value에 대해서 atomic type 뿐만 아니라, atomic type의 아이템을 갖는 Array 타입까지 지원하도록 업그레이드 하는게 어떤가요?

Express query에서는 단일 값이 전달되면 string으로 처리되고, 여러 값이 전달되면 array로 처리됩니다.

하지만 인터페이스에서 Array 타입으로 값이 정의되면, 값이 전달되지 않거나 단일 값이 전달되더라도 항상 array 타입으로 캐스팅하는 것이 일관성을 유지하는 데 도움이 될 것입니다. (그리고 배열 아이템도 모두 캐스팅해야 할 것입니다.)

특히 Typia에서 minItems와 maxItems comment tag를 사용하면, 값이 전달되지 않거나 단일 값이 전달되는 경우에 대해서도 제어할 수 있습니다.

---
What if TypedQuery is upgraded to support not only atomic types but also Array types that contain items of atomic types for object values?

In Express queries, if a single value is passed, it is treated as a string, and if multiple values are passed, they are treated as an array.

However, defining values as Array types in interfaces and casting them as arrays even when a single value is passed (or no value is passed at all) would provide consistency.(and each item have to be casted.)

Using minItems and maxItems comment tags in Typia could also help control cases where no value or a single value is passed.

**Comment by samchon** [comment]
Duplicated with #302

**Comment by samchon** [comment]
Same thing
