### ISSUE TITLE
Using nestia in nx/webpack

### ISSUE THREAD

**Issue by AliYusuf95** [samchon/nestia#319]
## Question
I'm planning to use `nestia` in my nx+nest.js project.

I have to do this to make `typia` and `nestia` transformers work without `ts-patch`.

> I would suggest to have built-in support for this just by adding `before` export.

```json5
// project.json
  "targets": {
    "build": {
      "executor": "@nrwl/webpack:webpack",
      "options": {
        "target": "node",
        "compiler": "tsc",
        ....
        "webpackConfig": "apps/api/webpack.config.ts",
        "transformers": [
          "apps/api/transformers/nestia.ts",
          "apps/api/transformers/typia.ts"
        ]
      },
```
```ts
// nestia.ts
import type * as ts from 'typescript';
import transform from '@nestia/core/lib/transform';

export const before = (options: Record<string, any>, program: ts.Program) => {
  return transform(program, options);
};
```
```ts
// typia.ts
import type * as ts from 'typescript';
import transform from 'typia/lib/transform';

export const before = (options: Record<string, any>, program: ts.Program) => {
  return transform(program, options);
};
```

But unfortunately it's not the case with `npx nestia sdk` and `npx nestia swagger`. 
Is there other way to use these commands without having to install `ts-patch`? e.g. having the generator as transformer that can be used after code compilation with options instead of having `nestia.config.ts`.

**Comment by samchon** [comment]
I do not have insight about this issue. Therefore, I will ask you something:

1. Why do you use webpack in backend project?
2. The before functions just look like parameters atlre reversed. Why it required?

Also, not possible to replace nestia.config.ts file by transform options, as nestia do not really execute the backend server, but just only analyze its codes and structuress.

Anyway, if you have clear insight and know how to solve, it is okay to send a PR including website content (maybe setup.mdx)

**Comment by tsa96** [comment]
I'm in the middle of moving our codebase over to Nx and the way [@nx/nest](https://nx.dev/packages/nest) uses webpack has struck me as very odd, with significant numbers asking for a way to disable it: https://github.com/nrwl/nx/discussions/8482.

So my (relatively uninformed) answer to 1. would be: it's just a weird part of Nx's design and probably quite hard for them to change it.

Doesn't really seem like an issue with this repo, rather Nx's fault for not being flexible enough.

**Comment by Vector-Green** [comment]
> I do not have insight about this issue. Therefore, I will ask you something:
> 
> 1. Why do you use webpack in backend project?
> 2. The before functions just look like parameters atlre reversed. Why it required?
> 
> Also, not possible to replace nestia.config.ts file by transform options, as nestia do not really execute the backend server, but just only analyze its codes and structuress.
> 
> Anyway, if you have clear insight and know how to solve, it is okay to send a PR including website content (maybe setup.mdx)

1.
- Ability to use terserPlugin and minify code
- Possibility of bundling node_modules inside bundle, output would be completely independent of node_modules folder
- Usage of pkg to build executable instead of js server)
currenlty I'm using babel instead of tsc
with config 
```ts
module.exports = {
  presets: ['@babel/preset-typescript'],
  plugins: [
    ['@babel/plugin-proposal-decorators', { legacy: true }],
    'babel-plugin-transform-typescript-metadata',
    '@babel/plugin-transform-runtime',
  ],
};
```
I'm getting 
```
Error: Error on nestia.core.TypedRoute.Post(): no transform has been configured. Run "npx typia setup" command.
    at t.TransformError
    ```

**Comment by samchon** [comment]
> > I do not have insight about this issue. Therefore, I will ask you something:
> > 
> > 1. Why do you use webpack in backend project?
> > 2. The before functions just look like parameters atlre reversed. Why it required?
> > 
> > Also, not possible to replace nestia.config.ts file by transform options, as nestia do not really execute the backend server, but just only analyze its codes and structuress.
> > Anyway, if you have clear insight and know how to solve, it is okay to send a PR including website content (maybe setup.mdx)
> 
> 
> * Ability to use terserPlugin and minify code
> * Possibility of bundling node_modules inside bundle, output would be completely independent of node_modules folder
> * Usage of pkg to build executable instead of js server)
>   currenlty I'm using babel instead of tsc
>   with config
> 
> ```ts
> module.exports = {
>   presets: ['@babel/preset-typescript'],
>   plugins: [
>     ['@babel/plugin-proposal-decorators', { legacy: true }],
>     'babel-plugin-transform-typescript-metadata',
>     '@babel/plugin-transform-runtime',
>   ],
> };
> ```
> 
> I'm getting
> 
> ```
> Error: Error on nestia.core.TypedRoute.Post(): no transform has been configured. Run "npx typia setup" command.
>     at t.TransformError
> ```

Babel removes every type info, therefore cannot be used in nestia

**Comment by Vector-Green** [comment]
Is there a list of supported compilers)? instead of babel)

**Comment by samchon** [comment]
Only TypeScript

**Comment by Vector-Green** [comment]
By the way, may I ask plz why ts-runtime-type-checking is faster then just using decorators)?
Seems none, babel and swc are not supporting runtime type checking

**Comment by Vector-Green** [comment]
Are there any examples of nestia+webpack)?

**Comment by Vector-Green** [comment]
I tried to use
```ts
 {
            test: /\.(ts|tsx)$/,
            use: [
              {
                loader: 'ts-loader',
                options: {
                  transpileOnly: true,
                  allowTsInNodeModules: true,
                },
              },
            ],
          },
          {
            test: /\.(js|cjs|mjs|jsx)$/,
            use: [
              {
                loader: 'swc-loader',
              },
            ],
          },
          ```
         but when trying to import 
         import { TypedParam } from '@nestia/core';
         ```
ERROR in ./src/app.controller.ts
Module build failed (from ./node_modules/.pnpm/ts-loader@9.4.3_typescript@4.9.5_webpack@5.84.1/node_modules/ts-loader/index.js):
TypeError: Cannot read properties of undefined (reading '0')
```

**Comment by samchon** [comment]
@Vector-Green This article may help you to understand why `typia` (`nestia`) is faster than `class-validator`

https://dev.to/samchon/typia-15000x-faster-validator-and-its-histories-1fmg

**Comment by samchon** [comment]
Also, I've not used webpack in NestJS environment at all.

Can anyone help us?

**Comment by MatznRisto** [comment]
We also use nest with nx. Found out about typia and nestia. Our company currently uses nx and nest with class-validators.

Would be great if there is support for webpack there.  Would help, but i am not that good with webpack. Will also investigate it. 

@samchon Thank you for you help.

**Comment by samchon** [comment]
As I've no chance to use it, no way for me. Can anybody help them?

**Comment by samchon** [comment]
Will someone try below way? 

## 1. Install `webpack` manually
```bash
npm install --save-dev webpack webpack-cli webpack-node-externals
```

## 2. Configure `webpack.config.js` file
```js
const path = require("path");
const nodeExternals = require('webpack-node-externals');

module.exports = {
    externals: [nodeExternals()],
    entry: ['./src/main.ts'],
    output: {
        path: path.join(__dirname, 'dist'),
        filename: 'main.js',
    },

    mode: 'development',
    target: 'node',
    module: {
        rules: [
            {
                test: /\.ts$/,
                exclude: /node_modules/,
                loader: 'ts-loader',
            }
        ]
    },
    resolve: {
        extensions: ['.tsx', '.ts', '.js'],
    },
    optimization: {
        minimize: false
    },
};
```

## 3. Run `webpack` command
```bash
npx webpack
```

**Comment by MatznRisto** [comment]
Sounds like a good path, what i tried did not work. But i think it still needs some tweaks, so that you can use it with nx executors. Will try it  next week and check if i can bring it to work.

Thank you.

**Comment by honguyenhaituan** [comment]
I just fix this by updating transformers in project.json 
```
"transformers": [
  "typia/lib/transform",
  {
    "name": "@nestia/core/lib/transform",
    "options": {
      "validate": "assert",
      "stringify": "assert"
    }
  }
]
```

**Comment by samchon** [comment]
Good job, can you write a documentation PR about it?

https://github.com/samchon/nestia/blob/master/website/pages/docs/setup.mdx

**Comment by honguyenhaituan** [comment]
@samchon I just update the documentation.  

https://github.com/samchon/nestia/pull/536

**Comment by samchon** [comment]
Published

**Comment by AwesomeAdventure** [comment]
> I just fix this by updating transformers in project.json
> 
> ```
> "transformers": [
>   "typia/lib/transform",
>   {
>     "name": "@nestia/core/lib/transform",
>     "options": {
>       "validate": "assert",
>       "stringify": "assert"
>     }
>   }
> ]
> ```

Looks like it's not working on latest nx version, also I have broken import of libs when this transformers specified in project.json

**Comment by honguyenhaituan** [comment]
Hi @AwesomeAdventure , I think the default of webpack config of nx is {transpileOnly: true}. I think real solution is turn it off. 

```
const { composePlugins, withNx } = require('@nx/webpack');

module.exports = composePlugins(withNx(), (config) => {
	config.module.rules.forEach((rule) => {
		if (rule.options?.transpileOnly) {
			rule.options.transpileOnly = false;
		}
	});
	return config;
});
```

**Comment by honguyenhaituan** [comment]
I make the newest version nx (18.2.4) run with nestia in this example repo. See commit: https://github.com/honguyenhaituan/nx-typia/commit/c1df98cf949b84633448d9ec4edbcef3635a0927
