### ISSUE TITLE
Featuer Request: How about throw BadRequest when invalid type error in @TypedQuery.

### ISSUE THREAD

**Issue by industriously** [samchon/nestia#320]
@TypedQuery 데코레이터는 유효하지 않은 타입이 확인되면, 일반적인 에러를 throw합니다. 저는 @TypedQuery가 @TypedBody, @TypedParam처럼 BadRequestException을 throw하는 것이 일관성있어 보인다고 생각합니다. 어떤가요?

The @TypedQuery decorator currently throws a general error when an invalid type is detected. I believe that it would be more consistent if @TypedQuery threw a BadRequestException like @TypedBody and @TypedParam do. What do you think?"

**Comment by samchon** [comment]
Good idea, but do not use Korean please.

Anyway, upgrade to `@nestia/core@1.1.1`, then become as you wish.
