### ISSUE TITLE
Missing examples of usage of Nestia

### ISSUE THREAD

**Issue by d-ivashchuk** [samchon/nestia#345]
## Question

I feel like I am missing the examples or sample nest app + nestia that would allow me to play around with the library quickly. Is there anything like that that I missed?

Thanks a lot for the great work @samchon!

**Comment by d-ivashchuk** [comment]
Just found this:

https://github.com/samchon/nestia-template

**Comment by samchon** [comment]
By the way, I also think that full level example project is required. Cannot sure when, but would be published.
