### ISSUE TITLE
`Prisma.JsonValue` occurs `Maximum call stack size exceeded`

### ISSUE THREAD

**Issue by dohyuu** [samchon/nestia#346]
### Summary

When there is a `Prisma.JsonValue` type in the `User` model of Prisma, an error occurs.

Actual behavior: error occurred

```bash
Maximum call stack size exceeded - src/app.controller.ts.8:49.
```

```prisma
// schema.prisma

model User {
  id    Int     @id @default(autoincrement())
  email String  @unique
  name  String?

  // here
  content Json?
  posts Post[]
}

model Post {
  id        Int     @id @default(autoincrement())
  title     String
  content   String?
  published Boolean @default(false)
  author    User    @relation(fields: [authorId], references: [id])
  authorId  Int
}
```

```typescript
// app.contoller.ts

@Controller('/')
export class AppController {
  /**
   * Maximum call stack size exceeded
   */
  @TypedRoute.Get()
  callStackExceeded(): User[] {
    return [];
  }

  /**
   * Ok
   */
  @TypedRoute.Get()
  noProblem(): Post[] {
    return [];
  }
}
```

If I comment out `callStackExceeded`, no error occurs.

### Code occuring the bug

repo: https://github.com/dohyuu/nestia-reproduce

```bash
git clone https://github.com/dohyuu/nestia-reproduce
cd ./nestia-reproduce
npm i
npm run db:gen
npm run start:dev
```

**Comment by dohyuu** [comment]
```typescript
  export type JsonObject = {[Key in string]?: JsonValue}

  /**
   * From https://github.com/sindresorhus/type-fest/
   * Matches a JSON array.
   */
  export interface JsonArray extends Array<JsonValue> {}

  /**
   * From https://github.com/sindresorhus/type-fest/
   * Matches any valid JSON value.
   */
  export type JsonValue = string | number | boolean | JsonObject | JsonArray | null
```

Here is the Prisma.JsonValue type.

**Comment by DavidVaness** [comment]
Just ran into this today

**Comment by samchon** [comment]
@dohyuu Due to `type JsonValue = ... | JsonValue[]` declaration, analyzing is not possible.

What about just using `any` type in that case?

**Comment by samchon** [comment]
@DavidVaness This issue needs entire refactoring in `typia`. I'll do this. Thanks

**Comment by dohyuu** [comment]
I solved the problem with a prisma interface generator that was customized for me. (`Prisma.JsonValue` is also replaced with `any`.)

Thank you for your feedback.

**Comment by samchon** [comment]
@dohyuu @DavidVaness 

Building and publishing next version of `nestia`. 

After a day, upgrade to `@nestia/core@1.3.0` and `@nestia/sdk@1.3.0`, then everything would be fine.

**Comment by DavidVaness** [comment]
Thank you @samchon 
Will report back on Monday

**Comment by DavidVaness** [comment]
@samchon I have updated to the latest typia + nestia and the issue persists. Only way is to remap the Prisma.Json to any or some other type

**Comment by samchon** [comment]
@DavidVaness Tested your code, but there's not any problem.

Which version are you using? 

If same error being repeated, can you provide me a reproducable repo?

  - DTO: [@typescript-eslint/no-empty-interface](https://github.com/samchon/nestia-issue-346/tree/master/src/api/structures/app)
  - Controller: https://github.com/samchon/nestia-issue-346/blob/master/src/controllers/AppController.ts
  - Test: https://github.com/samchon/nestia-issue-346/blob/master/test/features/api/app/test_api_app_users.ts
