### ISSUE TITLE
[BUG][sdk] Issue with inferred return type of object literals

### ISSUE THREAD

**Issue by angelhdzmultimedia** [samchon/nestia#380]
## Bug Report
Note that, the bug you're reporting may have registered in the [issues](https://github.com/samchon/nestia/search?type=issues) by another user. Even the bug you're reporting may have been fixed in the `@next` version. In such reasons, I recommend you to check the old [issues](https://github.com/samchon/nestia/search?type=issues) and reproduct your code with the `@next` version before publishing the bug reporting issue.

```bash
`npm install --save-dev nestia@next`
```

When the same error occurs even in the `@next` version, then please fill the below template:

### Summary
Issue with inferred return type of object literals

  - **SDK Version**: 1.3.9
  - **Expected behavior**:  All types of  my controllers, either parameters types or return type, resolved correctly.
  - **Actual behavior**:  Inferred return types of methods that return object literals, resolve to an undefined object `__object` and it's imported in api/functional/index.ts.

Write detailed description in here.

I have the `@core.TypedBody() body: LoginData` parameter in the `/auth/login` POST route of the AuthController.
I return the body and let TS infer the return type.
The type  `LoginData` for the body parameter gets imported in the generated client sdk successfully and set as input and output types.

But in the `/auth/user` GET route, I return an object literal `{}`, and no return type.
Instead of having the built-in type `object` as type for the output, it adds an import `__object`, but because I'm not defining a type or interface `__object`, it is of course undefined and throws the expected error shown in a screenshot (shown below).

### Solution Attempt
I then set the return type for the /auth/user route to `object` and it fixed it.

### Code occuring the bug
```typescript
/* Demonstration code occuring the bug you're reporting */
```

Write the demonstration code occuring the bug you're reporting.
![image](https://github.com/samchon/nestia/assets/10191085/cd07eecd-c848-46d5-96e7-5f67882faeae)

![image](https://github.com/samchon/nestia/assets/10191085/5b2a11c8-1670-4ab2-8d45-779b4518d535)

However, as the `nestia` is not a typical library who being used by the `import` statement but a executable program generating the SDK (Software Development Kit), it would be difficult to describe the bug with only the demonstration code.

In that case, you'd better to make a demonstration project occuring the bug to report. After the demonstration repository composition, fill the below `bash` script section. Of course, if you can describe the bug clearly, without the demonstration project construction, just skip it. Creating the demonstration repository is not essential.

```bash
git clone https://github.com/someone/nestia-bug-report-xxx
cd nestia-bug-report-xxx
npx nestia sdk
```

**Comment by samchon** [comment]
Write exact return type explicitly please.

I should make it an error with detailed message.

**Comment by angelhdzmultimedia** [comment]
> Write exact return type explicitly please.
> 
> I should make it an error with detailed message.

I'm confused. Are you suggesting that in order to solve this library generating a strange type, I have to put explicit return type?

Please help me understand.

**Comment by samchon** [comment]
Nestia is planned to generating SDK library for client developers.

If return type is not defined as an independent DTO, how client developer use it?

Do they have to define duplicate DTO structure looking at object literal expression in your backend server code?

I think this is not sensible.

**Comment by angelhdzmultimedia** [comment]
I read the Code of Conduct.

**Did you know respect goes both ways?**

You first marked my issue as [invalid], then closed it arrogantly, without even trying to explain why you decided to generate a made up type `__object` for object literals instead of using the TypeScript built-in `object` type, which is what's causing this issue  in the first place. 

I even went to the generated api/functional/auth/index.ts, removed the __object from the import, and replaced it everywhere with `object` and it fixed the issue. Because I love to experiment with stuff, before having to open Issues and waste other people's time and energy.

But if this is how you are going to treat consumers and possibly contributors (I love to contribute), then I'm not going to consume or contribute to anything made by you.

I just got a very bad vibe from you and I deal with many maintainers daily, many of them are kind, they take their time to explain, to understand, etc. 

I think you are suffering from the Dunning-Kruger syndrome, judging by all the badges you have earned, one of the badges even calls you a "god". I recommend keeping your humility in touch.

I was very hopeful with this library. It sounded great with the premise of 


> Only one line required, with pure TypeScript type
> 
> Runtime validator is 20,000x faster than class-validator
> 
> JSON serialization is 200x faster than class-transformer
> 
> SDK is similar with [tRPC(opens in a new tab)](https://trpc.io/), but much advanced
> 

But if the creator/maintainer is going to treat me like this, not even using kind words or greetings to let me know the intention behinds his words to create a non-toxic relationship, then I'll have to find another alternative.

Even though I was left with a bitter taste, I'm going to wish you health, peace, and success.

**Comment by samchon** [comment]
Sorry for rapid decision without detailed explanation. I will explain the detailed reason why probiting implicit type, even if it is too late.

In TS compiler, `__object` named type comes when array or object literal expression being used without any type definition. It is possible to analyze those literal expressions by make virtual types. Actually, `typia` and `@nestia/core` are already doing it.

However, considering purpose of SDK that delivering to client developers, such imperfection  should not be allowed. Delivered API spec must be clear and have not to make client developers to read backend server code just for understanding DTO spec.

**Comment by angelhdzmultimedia** [comment]
> Sorry for rapid decision without detailed explanation. I will explain the detailed reason why probiting implicit type, even if it is too late.
> 
> In TS compiler, `__object` named type comes when array or object literal expression being used without any type definition. It is possible to analyze those literal expressions by make virtual types. Actually, `typia` and `@nestia/core` are already doing it.
> 
> However, considering purpose of SDK that delivering to client developers, such imperfection should not be allowed. Delivered API spec must be clear and have not to make client developers to read backend server code just for understanding DTO spec.

Wow. That's the kind response I expected, but didn't imagine I would get. Thank you a lot for that.

(Don't want to use my condition or justify my words, but I suffer from Generalized Anxiety and depression and even the easiest task gives me a hard time, I'm always expecting the worse). 

With that said, I did my own experimentation and ChatGPT also helped me and I achieved why I needed with the following code:

```ts
import * as ts from 'typescript'

function getReturnTypesFromControllers(
  controllerFilePaths: string[],
): string[] {
  const program = ts.createProgram(controllerFilePaths, {})
  const typeChecker = program.getTypeChecker()

  const returnTypes: string[] = []

  for (const filePath of controllerFilePaths) {
    const sourceFile = program.getSourceFile(filePath)

    if (sourceFile) {
      ts.forEachChild(sourceFile, (node) => {
        if (ts.isClassDeclaration(node)) {
          const className = node.name
          if (className) {
            const controllerSymbol = typeChecker.getSymbolAtLocation(className)
            if (controllerSymbol) {
              const classType =
                typeChecker.getDeclaredTypeOfSymbol(controllerSymbol)
              const properties = typeChecker.getPropertiesOfType(classType)

              for (const property of properties) {
                const propertyDeclaration = property.valueDeclaration
                if (
                  propertyDeclaration &&
                  ts.isMethodDeclaration(propertyDeclaration)
                ) {
                  const signature =
                    typeChecker.getSignatureFromDeclaration(propertyDeclaration)
                  if (signature) {
                    const returnType =
                      typeChecker.getReturnTypeOfSignature(signature)
                    const returnTypeString =
                      typeChecker.typeToString(returnType)
                    returnTypes.push(returnTypeString)
                  }
                }
              }
            }
          }
        }
      })
    }
  }

  return returnTypes
}

// Usage example
const controllerFilePaths = ['src/auth/auth.controller.ts']
const returnTypes = getReturnTypesFromControllers(controllerFilePaths)
console.log(returnTypes)

```

`src/auth/auth.controller.ts`

```ts
import { Controller, Get, Post } from '@nestjs/common'
import { AuthService } from './auth.service'
import core from '@nestia/core'

export interface LoginData {
  email: string
  password: string
}

export interface RegisterData {
  email: string
  password: string
  firstname: string
  lastname: string
  username: string
}

@Controller('auth')
export class AuthController {
  constructor(private readonly authService: AuthService) {}

  @core.TypedRoute.Post('login')
  public login(@core.TypedBody() body: LoginData): LoginData {
    return body
  }

  @core.TypedRoute.Post('register')
  public register(@core.TypedBody() body: RegisterData): RegisterData {
    return body
  }

  @core.TypedRoute.Get('user')
  public user() {
    return {}
  }

  @core.TypedRoute.Get('test')
  public test(): object {
    return {}
  }
}

```

### Code Result Screenshot
![image](https://github.com/samchon/nestia/assets/10191085/d72a29ce-9fd2-45a6-ae76-3bbb80bfab2a)


I hope this time I could be useful to solve the issue with Nestia instead of waiting for someone else to solve it.
Also this motivated me to try and make my own "mini library" to replicate Nestia, and also add my own transforms/field validation.

Also, yes **I'm a strong advocate for being explicit**, I always mark my return types even for `:void`. It was just a curiosity, after I created a Nest project very quickly with some dummy code,  about why Nestia sdk didn't used the object type for an object literal, instead of using the made-up type `__object`.

Thank you for taking the time to understand my frustration and my intention which is based on good faith.

My apologies for any typo, my main language is Spanish.
