### ISSUE TITLE
SDK: How to access request object

### ISSUE THREAD

**Issue by DavidVaness** [samchon/nestia#402]
## Question
When awaiting the api data, the client directly returns the value the response of the request. 
I'd suggest to return the whole response object and set the returned value into the data property + it's type (similar to axios?)

In my case, I only needed the status code.

**Comment by samchon** [comment]
Can you show me an example or destination interface what you want?

**Comment by DavidVaness** [comment]
I think this could go multiple ways, but as you are wrapping fetch anyways, you could use the Response type, altered to already include the result in some key. 
Axios uses the data key. 
here is the response schema of [axios](https://axios-http.com/docs/res_schema) 
so you do 
```ts
const { data } = await axios.get<TypeHere>('example.com')
// or to access the rest
const response = await axios.get<TypeHere>('example.com')
```

**Comment by samchon** [comment]
Will find a way and developer at next month

**Comment by DavidVaness** [comment]
there is also this library here which might inspire you 
https://github.com/sindresorhus/ky

**Comment by DavidVaness** [comment]
Ty @samchon good job with the release
