### ISSUE TITLE
If the authorization header and @setHeader are listed together

### ISSUE THREAD

**Issue by kakasoo** [samchon/nestia#403]
Invalid SDK is generated. The connection object of the code written in the SDK is different from the type of IConnection.

# setting

```typescript
// nestia.config.ts
{
  swagger: {
    ...
    output: 'swagger.json',
    security: {
      bearer: {
        type: 'http',
        scheme: 'bearer',
      },
    },
  },
};

```
```typescript
// some api
/*
 * @tag auth
 * @setHeader authorization
 */
@UseGuards(JwtAuthGuard)
@TypedRoute.Get(':id/profile')
async getMyProfile() {}

```
```typescript
export interface IConnection {
    /**
     * Host address of the remote HTTP server.
     */
    host: string;
    /**
     * Header values delivered to the remote HTTP server.
     */
    headers?: Record<string, string> & Record<'authorization', string>;
    /**
     * Encryption password of its closure function.
     */
    encryption?: IEncryptionPassword | IEncryptionPassword.Closure;
}
```
# problem (type error)
```typescript
// nestia sdk
export async function getMyProfile(
  connection: IConnection,
  targetUserId: string,
): Promise<getMyProfile.Output> {
  const output: getMyProfile.Output = await Fetcher.fetch(
    connection,
    getMyProfile.ENCRYPTED,
    getMyProfile.METHOD,
    getMyProfile.path(targetUserId),
  );

  // configure header(s)
  connection.headers ??= {}; // here!
  connection.headers.authorization = output.authorization;

  return output;
}

```

**Comment by samchon** [comment]
Why this occurs error? Can you provide a reproducable repo?

**Comment by kakasoo** [comment]
@samchon 

```typescript
// configure header(s)
connection.headers ??= {}; // here!
connection.headers.authorization = output.authorization;
```

type `IConnection` is Record<string, string> & Record<'authorization', string>.
So, connection.headers can not be empty object. ( = `{}` )

**Comment by kakasoo** [comment]
```typescript
connection.headers ??= { authorization: '' }
```

This seems more appropriate (or the value of the authorization header is null)

**Comment by samchon** [comment]
Show me the TypeScript error message

**Comment by kakasoo** [comment]
<img width="603" alt="image" src="https://github.com/samchon/nestia/assets/55487286/85cc8bb4-f193-402d-b99b-82266ffcb93c">

Sorry, this is a side project for my team, so I can't share it externally. However, I don't think we need to share the code because this is a simple implementation error. Do you need a code? Then I will make a repo that can reproduce the problem and give it to you.

**Comment by samchon** [comment]
Does `Output` has the `authorization` property?

No compilation error occurs in my program

https://github.com/samchon/nestia/blob/master/test/features/encrypted/src/api/functional/sellers/authenticate/index.ts

**Comment by kakasoo** [comment]
I made an issue to inform this, so if you don't think it's a problem, it's okay to close this issue. :)

**Comment by samchon** [comment]
Show me a reproducable repo occuring compilation error

**Comment by kakasoo** [comment]
This was my problem. (Embarrassed)
