### ISSUE TITLE
[Suggestion] Add credentials propery to IConnection 

### ISSUE THREAD

**Issue by SeungjunWe** [samchon/nestia#411]
## Feature Request
add [credentials property](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch#sending_a_request_with_credentials_included) to IConnection
```typescript
export interface IConnection {
  credentials?: RequestCredentials;
}
```

## Examples of usage include
```typescript
import { functional } from 'sdk-created-by-nestia''

functional.user.getInfo({
  host: 'http://127.0.0.1',
  credentials: 'include',
})
```

**Comment by samchon** [comment]
Published as v1.4.0 update.
