### ISSUE TITLE
swc support

### ISSUE THREAD

**Issue by ilterugur** [samchon/nestia#416]
Hello, nestjs team announced that nestjs now supports swc thanks to the v10 update. As I see, nestia doesn't support it because typia doesn't support swc. Is it possible to support swc on future? Thank you.

**Comment by DavidVaness** [comment]
here is the related typia thread
https://github.com/samchon/typia/issues/146

**Comment by samchon** [comment]
Not possible, because SWC does not validate TypeScript type. It just removes every TypeScript type infos.

Instead, SWC developer is developing STC project. I will support it instead.

  - https://github.com/dudykr/stc

**Comment by samchon** [comment]
As you can see from the NestJS manual, `swc` does not perfor any type checking itself, but the type checking is done by `tsc`.

If you use the `nest start -b swc --type-check` command, you're not using `swc`, but `tsc` with `--noEmit` option. As `tsc` does not generate any JS files, it doesn't mean anything.
