### ISSUE TITLE
Nestia + Nextjs?

### ISSUE THREAD

**Issue by mthmcalixto** [samchon/nestia#440]
Excuse my ignorance, but can I use this separately with next js?
Nestia as backend and Nextjs as frontend, as well as tRPC?

**Comment by samchon** [comment]
Build SDK and import it in NextJS project.

**Comment by mthmcalixto** [comment]
> Build SDK and import it in NextJS project.

any example?

**Comment by samchon** [comment]
No example, but easy. Do it following this guide:

  - https://nestia.io/docs/sdk/sdk/#distribution
