### ISSUE TITLE
How to do authentication with nestia?

### ISSUE THREAD

**Issue by Nethrenial** [samchon/nestia#476]
#  How to implement various authentication patterns used in nestjs with nestia? '

Does it support the same kinds of guards we write for passport js with nestjs?If it does, how to pass the Bearer token with auto-generated client SDK of nestia?

**Comment by samchon** [comment]
# 1. Using comment tags
https://nestia.io/docs/sdk/sdk/#comment-tags

## 2. Manual assignment on `IConnection.headers`
```typescript
const reply = await api.functional.some.address(connection, ...);
connection.headers ??= {};
connection.headers.Authorization = reply.token;
```
