### ISSUE TITLE
How to use @nestia/fetcher with webpack? (impor2 Critical dependency issue)

### ISSUE THREAD

**Issue by gabrielDonnantuoni** [samchon/nestia#482]
First I'd like to congratulate you @samchon for this great work you are doing with nestia and typia. It's really beatiful.

## Context
I'm using @nestia/sdk to consume my backend on a next.js project, that uses webpack.

## Problem
Webpack doesn't handle dynamic imports. I get the following error when I try to consume the api.

```
- ready started server on 0.0.0.0:3000, url: http://localhost:3000
- event compiled client and server successfully in 282 ms (20 modules)
- wait compiling...
- event compiled client and server successfully in 70 ms (20 modules)
- wait compiling /page (client and server)...
- warn ../web-server/packages/api/node_modules/import2/index.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
../web-server/packages/api/node_modules/import2/index.js
../web-server/packages/api/node_modules/@nestia/fetcher/lib/Fetcher.js
../web-server/packages/api/node_modules/@nestia/fetcher/lib/index.js
../web-server/packages/api/lib/HttpError.js
../web-server/packages/api/lib/module.js
../web-server/packages/api/lib/index.js
./src/app/page.tsx
- error TypeError: fetch failed
- error TypeError: fetch failed
digest: "500536672"

```

## Question
I'm guessing that you are using the `import2` lib to support older nodejs versions that do support the fetch API natively.

So, do you know any workaround to make it work with the aforementioned setup?

**Comment by samchon** [comment]
Have you installed `node-fetch@2.6.7` on your `package.json`?

**Comment by gabrielDonnantuoni** [comment]
Since I'm using node18+ I've found a way patching out `import2` usage of @nestia/fetcher with `pnpm patch`. 
It's not a fix, just a workaround.
