### ISSUE TITLE
@nestia/migrate Is to change kebab case to snake case intended?

### ISSUE THREAD

**Issue by sunrabbit123** [samchon/nestia#512]
## Question

https://github.com/samchon/nestia/blob/master/packages/migrate/src/programmers/ControllerProgrammer.ts#L18-L20

At first glance, the following code works exactly as intended.
However, looking inside StringUtil, this is not the case at all.

```ts
export const split = (path: string) =>
    path
        .split("/")
        .map((str) => normalize(str.trim()))
        .filter((str) => !!str.length);

export const normalize = (str: string) =>
    str.split(".").join("_").split("-").join("_");
```

This code finds the `-` and replaces it with `_`
However, this code will cause the kebab case to turn into a snake upon migration

`/device-management/managed-devices ` to `/device_management/managed_devices`

Turning a bad convention into a good one is not a bad idea
However, the Restful API recommends a kebab case.

**Comment by samchon** [comment]
Good point, it is my mistake, and fixed the bug in `v0.2.2`
