### ISSUE TITLE
 query parameter miss Property "name" in swagger.

### ISSUE THREAD

**Issue by industriously** [samchon/nestia#521]
Swagger always requires the 'name' property to be mandatory for parameters.

in swagger editor error
<img width="618" alt="스크린샷 2023-08-04 오후 7 17 14" src="https://github.com/samchon/nestia/assets/116284195/8cab6110-d343-4aa9-bee9-502f4fb85d8b">

// related json
<img width="636" alt="스크린샷 2023-08-04 오후 7 21 56" src="https://github.com/samchon/nestia/assets/116284195/78ca8f73-1e5a-4638-baaa-f86d593085e3">

// fixed json
<img width="605" alt="스크린샷 2023-08-04 오후 7 20 45" src="https://github.com/samchon/nestia/assets/116284195/01bf16ad-1ca2-4120-a1a6-9cf514665d6e">

**Comment by samchon** [comment]
Fixed the bug. Upgrade to `@nestia/sdk@1.5.7`
