### ISSUE TITLE
In the "@nestia/migrate" package, how is the router handler function's name typically named?

### ISSUE THREAD

**Issue by industriously** [samchon/nestia#538]
Although similar naming conventions have been used in the past, I propose the following rules for consistency:

1. Start with the HTTP method.
2. If using HTTP parameters, follow the format methodByParamName. In this case, the parameter name follows Pascal case (or simply capitalize the first letter of the user-provided name).
3. No changes to naming based on http query or http body.

---

Currently in @nestia/migrate, even when utilizing HTTP parameters, the names were solely based on the HTTP method as long as there were no conflicts. However, this practice could change in the future when additional HTTP requests without using parameters are introduced. This scenario could lead to unforeseen conflicts, especially if a frontend developer utilizes @nestia/migrate to build a backend SDK based on an incomplete swagger.json.

I think, It's essential to be cautious of potential conflicts in such cases.

---

Currently in @nestia/migrate, if I define an HTTP parameter with the name `normal_id`, the corresponding handler name would be `methodByNormal_id`. I find it consistent to use `methodByNormalId` if I were to use the name `normalId`, but in reality, it becomes `methodByNormalid`. 

If this behavior is intentional, Could you please provide an explanation for this reasoning?

**Comment by industriously** [comment]
same content. (위 본문과 같은 맥락의 내용입니다.)

현재는 GET /users/:user_id 요청의 핸들러 이름은 users.get입니다. 하지만 만약 GET /users 요청이 추가로 개발되면 이전 요청의 핸들러 이름이 users.getByUser_id로 변경됩니다. 저는 처음부터 users.getByUser_id 로 작성되는 것을 제안하고 싶습니다.

그리고 핸들러 함수 이름을 무조건 파스칼케이스로 만들거나 하면 더 자연스러운 이름이 될 것 같습니다.
현재는 userId 라는 http parameter 이름을 사용해도 users.getByUserid 라고 작성됩니다.

**Comment by samchon** [comment]
It is to make method name shorter.

Your use case is abnormal due to migrate would not be repeated such a lot.
