### ISSUE TITLE
How to specify the error response types for swagger

### ISSUE THREAD

**Issue by loucass003** [samchon/nestia#540]
Using the nestjs swagger api, I used to set the response errors and code with the different decorators like so

```ts
  @Header('Cache-Control', 'no-cache')
  @ApiOperation({
    description: 'Build a specific configuration of the firmware',
  })
  @ApiOkResponse({ type: BuildResponseDTO })
  @ApiBadRequestResponse({ type: VersionNotFoundError })
  buildFirmware(@Body() body: CreateBuildFirmwareDTO) {
    return this.firmwareService.buildFirmware(body);
  }
  ```
  
  How can I specify those possible responses with nestia?

**Comment by loucass003** [comment]
it looks like a good way to support this could be to check the
``@throws`` and if the type is an http exception specifying the response code and the payload

Something like this perhaps?
```ts
  /**
   * @throws {import("./errors/version-not-found.error").VersionNotFoundExeption}
   */
   @TypedRoute.Post("/build")
  buildFirmware(@Body() body: CreateBuildFirmwareDTO) {
    return this.firmwareService.buildFirmware(body);
  }
  ```

```ts
export const VersionNotFoundError = 'Version not found';
export class VersionNotFoundExeption extends HttpException {
  constructor() {
    super(VersionNotFoundError, HttpStatus.BAD_REQUEST);
  }
}
```

**Comment by samchon** [comment]
Will support new decorator function `@TypedException<T>()`.

But as I'm working another thing (`typia.protobuf`), this feature would be implemented later.

**Comment by loucass003** [comment]
Is there at least a way to use both legacy decorators and nestia to generate a swagger document?

**Comment by samchon** [comment]
Good idea, I will.

**Comment by samchon** [comment]
https://github.com/samchon/nestia/pull/548

Upgrade to `v1.6.4`, then what you want would be prepared.
