### ISSUE TITLE
Suggest @nestia/sdk generate DTO types directly.

### ISSUE THREAD

**Issue by industriously** [samchon/nestia#550]
Currently, the @nestia/sdk directly imports SDK DTO interface defined by developers. This approach imposes the following constraints:
- All DTO interfaces and types that the DTO depend on must be under the builded sdk directory.
- The SDK build path must be located under the `src` directory.
Due to these limitations, there have been many instances where the adoption of Nestia has been hindered.

Therefore, similar to @nestia/migrate, I suggest that @nestia/sdk generate type information directly.

**Comment by samchon** [comment]
Will supported at next v2 update.
