### ISSUE TITLE
How to coerce type before validation?

### ISSUE THREAD

**Issue by SalvadorLekan** [samchon/nestia#552]
## Question

How do I coerce the type of input before validating? 

This is needed when the input is coming from a string source like `process.env`.

Example:
```ts
type ENV_VARS = {
  DATABASE_URL:string;
  PORT: string //What I want is actually a number with the extra validations that come with `number`.
  CI?: string //What I what is actually is a boolean.
}
```

I know this is possible to an extent within Nestia/Typia because `TypedQuery`, `TypedParams` and `TypedBody` do some transformations.

But I don't see it in any documentation on how to do it myself.

**Comment by samchon** [comment]
```${number}`

**Comment by samchon** [comment]
```ts
interface IEnv {
    port: `${boolean}`;
    ci: `${number}`;
}
```

**Comment by SalvadorLekan** [comment]
I already tried that.
What I got
1. Was still a string
2. `${number}` allows "-3.5'. I ideally want to validate `  @type uint` at least. (I was able to resolve this with @pattern but numbers comes with useful features like @minimum etc)

It would be great if this feature exists or is made obvious.

Thank you

**Comment by samchon** [comment]
No way yet. I'll consider another way like `${number & Type<"int"> & Minimum<(3>}`

**Comment by samchon** [comment]
Next week, I will publish this feature.

https://github.com/samchon/typia/pull/786

**Comment by SalvadorLekan** [comment]
Thank you!
That solves the problem of me trying to revalidate a number string.

But after spending more time with Nestia, I realized that what I really wanted was a type safe conditional transformation API.

I don’t know if it’s within the scope of Typia

Let me give some examples…

I have a 
```ts
type SupportedCountry = “NG”|”GB”|”AE”| “KE” //totally hypothetical 

interface IProduct {
  /**
  * @format email
  */
  email: ToLowerCase<string> // I want email in uniform casing 

  ships_from: SupportedCountry & ToUpperCase<MaxLength<2> & MinLength<2>> // Because I want to accept “ng” or “Ke” but want them to be capitalized then validated to be type SupportedCountry.

  ships_to: SupportedCountry[] & ToArray<SupportedCountry> // This is necessary because of the way most libraries parse “multipart/form-data“ if it receives only one item.

  available_stock: number & Type<“uint32”> & ToInt<`${Type<“uint32”>}`> // This again because “multipart/form-data” doesn’t have a way to specify type of field or because process.env returns all string and you want to safely validate and parse number fields.
}
```
The good thing about this kind of transformation is that you would a `never` or a Typescript error if you are transforming to the wrong type. 

What do you think?
Is it something within the scope of Typia or is it something that you would consider at all?

**Comment by samchon** [comment]
Your suggestion seems too difficult and domestic \o/.

Anyway, tried below approach, but it was not possible to use type tag in template type.

I'll ask it to TypeScript repo that it is bug or not.

![image](https://github.com/samchon/nestia/assets/13158709/b20e953f-d3f4-49ec-9fdd-cee91d687846)

**Comment by SalvadorLekan** [comment]
😅  I know it is domestic.

I just did this to communicate my intention clearly. Which may give you a direction.

Also, the conflict may be from your tags, not Typescript because I tried this and was not getting errors when I did a very basic replication.
![Screenshot from 2023-08-27 14-28-03](https://github.com/samchon/nestia/assets/66782276/44a109e7-f880-4a4b-a3e8-2149ff4439a6)

**Comment by samchon** [comment]
No way for a while. `typia`'s type tags are not supporting template literal type.

Sorry for not helpful.
