### ISSUE TITLE
support `string` message type in @TypedException<T>

### ISSUE THREAD

**Issue by industriously** [samchon/nestia#564]
1. support string type at error body.

as-is
```ts
export declare function TypedException<T extends object>(status: number | "2XX" | "3XX" | "4XX" | "5XX", description?: string | undefined): MethodDecorator;
```

to-be
```ts
export declare function TypedException<T extends object>(status: number | "2XX" | "3XX" | "4XX" | "5XX", description?: string | undefined): MethodDecorator;
export declare function TypedException<T extends string>(status: number | "2XX" | "3XX" | "4XX" | "5XX", description?: string | undefined): MethodDecorator;
```

---

2. in nestia 1.6.5v, TypedException is deprecated. Are there any other decorators planned to be developed?

**Comment by samchon** [comment]
Not deprecated, but just tagged on a function when not specify generic argument.

Also, nestjs does not support string typed schema in their exception class. How do you think about that?

**Comment by industriously** [comment]
> Not deprecated, but just tagged on a function when not specify generic argument.
> 
> Also, nestjs does not support string typed schema in their exception class. How do you think about that?

1. swagger schema support string type.
2. nestjs support all type of error body.(because httpAdapter.reply parameter type in filter is any)

**Comment by samchon** [comment]
Will support at v2 udpate.
