### ISSUE TITLE
Fetcher is mis-handling Connection header

### ISSUE THREAD

**Issue by ninthsun91** [samchon/nestia#598]
currently using,
- `@nestia/core` - 1.4.4
- `@nestia/sdk` - 1.4.12
- `@nestia/fetcher` - 1.6.7

After updating `@nestia/fetcher` recently I have problem with setting headers in client-side code, and it's because of [this commit](https://github.com/samchon/nestia/commit/1660ee1eb9eaff8965ed1d078b91ef4a94bc4df9) you've made which changes how `headers` is parsed from `IConnection`.

say I have `Connection` like below,

```ts
export const connection = (): IConnection => ({
  host: 'https://nestia.io/',
  headers: {
    'x-api-key': 'api-key',
    authorization: `Bearer token`,
  },
});
```

Before, this `Connection` object was spread into request headers, but now, it is wrapped in an array and showing in request header like below.
```
0: x-api-key,api-key
1: authorization,Bearer token
```

If this is not a intended behavior, I think [this part of the code (Fetcher.ts)](https://github.com/samchon/nestia/blob/1660ee1eb9eaff8965ed1d078b91ef4a94bc4df9/packages/fetcher/src/Fetcher.ts#L99) should be changed like this,
```ts
            headers: (() => {
                const output: [string, string][] = [];
                for (const [key, value] of Object.entries(headers))
                    if (value === undefined) continue;
                    else if (Array.isArray(value))
                        for (const v of value) output.push([key, String(v)]);
                    else output.push([key, String(value)]);
--              return output;
++              return Object.fromEntries(output);
```

if this was an intentional change, should I not set headers in `IConnection`?

**Comment by samchon** [comment]
Intended change, and no problem with it.
