### ISSUE TITLE
Support stringified JSON in @TypedQuery

### ISSUE THREAD

**Issue by jacquesg** [samchon/nestia#600]
Currently, `@TypedQuery` isn't as flexible as `@TypedBody`, making it quite hard to pass complex queries which may require nesting to `GET` requests.

The Loopback project has something calling "stringified JSON" which addresses this problem. Supporting this, I believe would bring `@TypedQuery` and `@TypedBody` closer in terms of flexibility, and ultimately help me port an application from Loopback to NestJS.

Reference: https://loopback.io/doc/en/lb4/Querying-data.html

**Comment by samchon** [comment]
This is too domestic feature that not defined in the standard spec.

**Comment by jacquesg** [comment]
I think you’re missing the point. GET requests don’t have bodies. If you read through the Loopback documentation, you’ll see that it is spec compliant. This is an encoding mechanism ultimately.

**Comment by samchon** [comment]
I think you'd better to use other methods like POST.

If `@TypedQuery()` supports JSON typed property, it would be a great hazard due to 2K length limit of URL path.
