### ISSUE TITLE
Q: Nestia without NestJs ?

### ISSUE THREAD

**Issue by Devidian** [samchon/nestia#601]
## Question
Hey, i've been added to a new project, where the CTO decided not to use nestjs. Instead they use pure express. The other devs had used typia until now but they noticed that typia alone does not convert number for example from query routes. Now they want to rollback to class- transformer/validator , .....
In my main project we have no problems as we use nestjs, so the question came up if nestia can somhow be used without nestjs? As my time for this second project is not fulltime, i thought its easier to ask here, maybe someone has already some experience.

Best Regards
Devidian

**Comment by samchon** [comment]
Planning to make `fastify` plugin utilizing `typia`, but cannot sure when.
