### ISSUE TITLE
Optional @TypedQuery query?: { foo: string }

### ISSUE THREAD

**Issue by radixxko** [samchon/nestia#612]
Hello,

is it possible to have optional @TypedQuery somehow? If we add questionmark after the parameter name it fails on

```Error on nestia.core.TypedQuery(): no transform has been configured.```

we need for swagger client, otherwise in swagger JSON query is marked as required

```
"parameters": [
        {
          "name": "query",
          "in": "query",
          "schema": {
            "$ref": "#/components/schemas/__type"
          },
          "description": "",
          "required": true
        }
 ]
```

Many THANKS!!!

**Comment by industriously** [comment]
query is required and i think query.foo is optional.

**Comment by industriously** [comment]
additionary every dto have to defined!
interface IFoo { foo?: string }

**Comment by radixxko** [comment]
Thanks for the fast reply, but should i be able to make whole query being optional by adding `?` there?

I would argue when you have type Partial<IFoo> or when every property in IFoo is optional it should set

```
"required": true
```

for swagger because currently when using swagger client you need to pass empty object as a query parameter otherwise it fails

**Comment by industriously** [comment]
if you want to define all property is optional, use Partial<DTO> type.

'query?: DTO' not means that all property is optional.

if you want to request api with not using query, in swagger, you have to add empty object.



so i recommand to use decompose mode.
in this mode, you dont have to add empty object.

**Comment by industriously** [comment]
"query?: { foo: string }"

this case is weired. because in type, foo is required. but query object is optional.

in rest api, what does that mean?

query object is not exist in http api concept.
and query parameter "foo" is required.

in conclusion, this case is weired.

i think, decompose mode is exactly a solution for your problem.

**Comment by radixxko** [comment]
I dont think the case is weird at all since you can have something like

```
@TypedQuery() query? : { limit: string, sort: string }
```

which should allow you having no query at all or force both `limit` and `sort` to be defined

**Comment by industriously** [comment]
> I dont think the case is weird at all since you can have something like
> 
> 
> 
> ```
> 
> @TypedQuery() query? : { limit: string, sort: string }
> 
> ```
> 
> 
> 
> which should allow you having no query at all or force both `limit` and `sort` to be defined
> 
> 
> 
> 

technically, query object is just express request.query and it is always exist object.
so query object is always required.

"query object" is just bucket that have all query value data. so bucket always exist even if no query case.

if you want to define no-query or all-query, it is union type.

like this

ex) query: { a: string;, b:string; } | {}

but technically, TypedQuery not support union type.

detail restriction info is descripted in offical docs.

**Comment by radixxko** [comment]
Yeah we know about a limitation, I will let you know tomorrow how we resolved that so you might add a hint to typedquery documentation since it might help somebody

**Comment by samchon** [comment]
https://nestia.io/docs/core/TypedQuery/#restriction

**Comment by samchon** [comment]
I got an idea. How about allowing the query parameter to be optional only when every properties are optional?

How do you think? @radixxko @industriously

**Comment by nullbytesoftware** [comment]
its weird that i cant have one query param optional in the object. Is tried `lang?` and `lang: string | null` both still throw 400

**Comment by singggum3b** [comment]
```
type TQuery = { // some typing } | undefined
@Query() query: TQuery
```
this should be valid (aliased type) where you can ref the alias
