### ISSUE TITLE
Fail to build sdk namespace-related DTO in clone mode.

### ISSUE THREAD

**Issue by industriously** [samchon/nestia#616]
version
"@nestia/sdk": "^2.0.4",
"typescript": "^5.2.2",

## Bug Report
- every type in namespace is missing.
- a dto with the same name as the namespace is missing.

<img width="404" alt="스크린샷 2023-09-19 오후 6 15 40" src="https://github.com/samchon/nestia/assets/116284195/dc0ffa34-e6a1-4878-8c08-9c0309ad501c">
<img width="619" alt="스크린샷 2023-09-19 오후 6 03 22" src="https://github.com/samchon/nestia/assets/116284195/3ae89f0a-5436-49d0-b78c-558c912a4dde">
<img width="448" alt="스크린샷 2023-09-19 오후 6 03 58" src="https://github.com/samchon/nestia/assets/116284195/2a583410-3578-4b0f-841a-c64dcdf35a91">

## Bug Test
1. clone project (branch: develop)
- [TEST Project](https://github.com/industriously/nestia-template/tree/develop)
2. project setup & build sdk
```bash
// download dependency
npm i
// build sdk to ./sdk
npm run sdk
```
3. check bug
- please check ./sdk/functional/users/normals/index.ts
- [related router code](https://github.com/industriously/nestia-template/blob/develop/src/controllers/users.ts)

**Comment by industriously** [comment]
@samchon bug is not completed in  "@nestia/sdk": "^2.0.5",

related @TypedException<T>(); 

<img width="398" alt="스크린샷 2023-09-22 오후 4 44 12" src="https://github.com/samchon/nestia/assets/116284195/ed4f6a3b-3c65-4e0d-9efe-7889278ee133">
<img width="468" alt="스크린샷 2023-09-22 오후 4 44 35" src="https://github.com/samchon/nestia/assets/116284195/f77e6554-f15f-42e1-8186-8de27b2bed07">

**Comment by samchon** [comment]
Upgrade to v2.0.6, then be fixed.
