### ISSUE TITLE
Problems that are always registered at the highest level when registering through RouterModule

### ISSUE THREAD

**Issue by hmmhmmhm** [samchon/nestia#63]
![스크린샷 2022-04-25 오전 11 23 46](https://user-images.githubusercontent.com/38493722/165010390-e59fcf25-f37b-4fe0-8807-2967261146dd.png)
![스크린샷 2022-04-25 오전 11 26 21](https://user-images.githubusercontent.com/38493722/165010625-66ccd015-846e-4333-848a-ab6dc85fb239.png)

When registering through RouterModule
It would be good to use path information in nestia.

**Comment by samchon** [comment]
As the `@Module` decorator function comes with the main program who really opens the backend server, it seems dangerous for the nestia to analyze it in the runtime level.

If someone has a good idea to solve this issue, please help me.

**Comment by samchon** [comment]
https://nestia.io/docs/sdk/sdk/#configuration

Upgrade to v2.3, then you can do it.

```typescript
import { INestiaConfig } from "@nestia/sdk";
import { Module, VersioningType } from "@nestjs/common";
import { NestFactory } from "@nestjs/core";

const NESTIA_CONFIG: INestiaConfig = {
    input: async () => {
        const app = await NestFactory.create(MyModule);
        app.setGlobalPrefix("api");
        app.enableVersioning({
            type: VersioningType.URI,
            prefix: "v",
        });
        return app;
    },
    output: "src/api",
    e2e: "src/test",
    swagger: {
        output: "swagger.json",
        security: {
            bearer: {
                type: "apiKey",
            },
        },
    },
};
export default NESTIA_CONFIG;
```
