### ISSUE TITLE
Using TypedBody with assertEqual in Nest.js

### ISSUE THREAD

**Issue by Val0429** [samchon/nestia#636]
## Question

I am attempting to use TypedBody with assertEqual instead of the default assert in a Nest.js application. Here's what I tried:

```
@TypedRoute.Put()
    update(
        @TypedBody({
            type: "assert",
            assert: typia.assertEqual,
        })
        updateUserDto: IUpdateUserDto,
    )
```
However, this results in an error, as depicted in the following image:
![image](https://github.com/samchon/nestia/assets/16552067/69a68938-b9bd-4a01-ac56-57c9348fdad3)

How can I successfully achieve this? Thank you.

**Comment by samchon** [comment]
You can do it by one of two ways below:

## 1. Global way
Configure `tsconfig.json` like below:

```json
{
  "compilerOptions": {
    "plugin": [
      {
        "transform": "@nestia/core/lib/transform",
        "validate": "assertEquals",
        "stringify": "assert"
      }
    ]
  }
}
```


## 2. Individual way
If you want to configure it individually, call `createAssertEqual` function instead.

```typescript
@TypedBody({
    type: "assert",
    assert: typia.createAssertEqual<IUpdateUserDto>(),
})
```
