### ISSUE TITLE
Is it possible to remove unknown fields?

### ISSUE THREAD

**Issue by TriPSs** [samchon/nestia#637]
## Question
Is it possible to transform an response object so it only contains the properties that are defined in the interface?

**Comment by TriPSs** [comment]
I am using a TypedRoute decorator, yet it still outputs fields that are not inside the interface.

**Comment by TriPSs** [comment]
I found the issue, first one works second one does not
```ts
export interface CreditCase {
  id: number & tags.Type<'uint32'>
}
```

```ts
@Authorize(CreditCaseAuthorizer)
export class CreditCase extends CreditCaseEntity {
  id: number & tags.Type<'uint32'>
}
```

Is there a way we can make the second one work?

**Comment by industriously** [comment]
use only interface for defining dto like first case.

**Comment by TriPSs** [comment]
Well we want/need to add additional info (see the decorator), that way works with everything except the stringify. 

With the first option we need to define the same 3 times, a bit mutch 😅

**Comment by TriPSs** [comment]
We can close this, everythings works as expected.
