### ISSUE TITLE
I have a problem with launching a project using nestia decorators

### ISSUE THREAD

**Issue by RumyantsevOleg** [samchon/nestia#655]
## Question
Hello, I am very interested in your library and decided to try it. I had a problem with running a project using nestia decorators.

I created a new project and tried to add typeia using the documentation.
But I get the error: Error: Error on nestia.core.TypedRoute.Get(): no transform has been configured. Run "npx typia setup" command, or check if you're using non-standard TypeScript compiler like Babel or SWC.
    at NoTransformConfigureError

I probably configured something wrong, please tell me. And it also seems to me that it would be a good idea to describe more examples of setting up a nestjs application along with typia and nestia (I mean creation from scratch or migration). I tried to generate a project using a command, the structure seemed inconvenient to me. It would be nice to have the simplest possible option for adding nestia to a project and not abandoning the nestjs structure.

**Comment by samchon** [comment]
https://nestia.io/docs/setup/

**Comment by RumyantsevOleg** [comment]
Thanks, but I already went through these documents

**Comment by samchon** [comment]
Link your project, then I can help you.

**Comment by RumyantsevOleg** [comment]
Sorry for the question. To be on the safe side, I decided to try to recreate the project from scratch. Last time I configured it using the Setup Wizard, there was some error. Now it's gone, perhaps you made changes or I performed the steps correctly and in the correct sequence. There is no problem now
