### ISSUE TITLE
Enhancing GET Request Flexibility for Parameter Parsing in Nestia

### ISSUE THREAD

**Issue by Val0429** [samchon/nestia#675]
## Feature Request

I'd like to request an enhancement for `Nestia` that allows for extended queries while using a **GET** request. This feature would be really helpful in certain situations.

For instance, [ZenStack](https://zenstack.dev/) provides a helpful format in its CRUD API like this: [LINK](https://zenstack.dev/docs/intro/api)
> GET /api/model/post/findMany?q={"where":{"published":true},"include":{"author":true}}

With the 'q' parameter, Prisma's `findMany` interface is exposed, which is very flexible and useful.

I'm wondering if it's possible to incorporate this kind of parameter parsing into `Nestia`. To explain in more detail, this would involve first using `JSON.parse` on the 'q' parameter's string, and then using `assertEqual` to validate the interface.

Thank you.

**Comment by samchon** [comment]
I hope you to make the router function to have another method like `PATCH`, and use `@TypedBody()` instead. 

The standard URL query allows only `Record<string, string | string[] | undefined>` type. I know there're some insane libraries or APIs writing JSON string on an URL query property, but it is not standard. Furthermore, the URL address has length limitation, so such raw JSON string assignment causes unexepcted error that hard to trace and debug.

This is the reason why `@TypedQuery()` decorator is not supporting the JSON format, and enforcing restriction following the standard spec. It is free that calling `JSON.stringify()` and `JSON.parse()` functions on a `string` typed property of `@TypedQuery()`, but `nestia` doesn't have plan to support such non-standard feature.

https://nestia.io/docs/core/TypedQuery/#restriction
