### ISSUE TITLE
[Suggestion] build sdk only using swagger docs

### ISSUE THREAD

**Issue by 2langk** [samchon/nestia#682]
## Feature Request
I wrote swagger document using spring boot.
and I want to build nestia sdk using swagger document. 
now, it is impossible to build only sdk using `@nestia/migrate` (it can generate sdk but also nestjs application)

so, I suggest options like `--sdk-only`  in `@nestia/migrate`

example)
`npx @nestia/migrate --sdk-only swagger.json output_directory`

**Comment by samchon** [comment]
https://github.com/samchon/nestia/issues/445

Good suggestion.

To accomplish above feature `@nestia/editor`, I should implement this issue, and it was one of my plan.

**Comment by samchon** [comment]
@2langk 

Completed 

https://nestia.io/docs/migrate/
