### ISSUE TITLE
Reject request body with unspecified attributes

### ISSUE THREAD

**Issue by PhilippAlbrecht-KR** [samchon/nestia#687]
## Question
Hey quick question since I didn't find anything in the docs or issues or by trying myself. Is there a way to fail a body, which has to many fields?

example:
![image](https://github.com/samchon/nestia/assets/89988973/d9cb02ff-476c-4748-9b76-e8c35e370f3f)
<img width="943" alt="image" src="https://github.com/samchon/nestia/assets/89988973/3346cc59-5bc3-47b1-b3fe-16acf185e375">

I would like to reject the requests since the interface has no _foobar_. Tried to set ts.config to assertEquals or validateEquals.
Example was written with the latest nestia setup

edit: something like `BadRequestException: Request body data is not following the promised type. Unexpected attribute foobar`

**Comment by samchon** [comment]
Configure `tsconfig.json` like below:

```json
{
  "compilerOptions": {
    "plugins": [
        { 
          "transform": "@nestia/core/lib/transform",
          "validate": "assertEquals",
        },
      ],
  }
}
```
