### ISSUE TITLE
@TypedQuery's openapi output is nested in the query parameter

### ISSUE THREAD

**Issue by ryosukemori** [samchon/nestia#723]
Thank you very much for a very nice package, we have been able to build validations very easily with Nestjs and have received a great experience.

It works correctly in most situations, but in @TypedQuery, when I output an OpenAPI schema, it becomes an object nested in parameters and I am unable to use fetch() with OpenAPI types in the front end.

Is there a workaround in Nestia to improve this?

```ts
@TypedRoute.Get()
  public async findMany(
    @TypedQuery() query: FollowFindManyQuery,
    @CurrentUser() user: User,
  ): Promise<UserPublicResponse[]> {
    console.log(query)
    return this.followsService.findMany(query, user)
  }
```

<img width="300" alt="image" src="https://github.com/samchon/nestia/assets/32259709/69c60ae5-7b02-42a8-a35c-5dd77d90a82c">

```json
"get": {
        "tags": [],
        "parameters": [
          {
            "name": "query",
            "in": "query",
            "schema": {
               // in query nest object
              "$ref": "#/components/schemas/FollowFindManyQuery"
            },
            "description": "",
            "required": true
          }
        ],
```

**Comment by samchon** [comment]
Configure `INestiaConfig.swagger.decompose` property to be `true`, then it would be decomposed.

![image](https://github.com/samchon/nestia/assets/13158709/83cad5d5-b780-45bd-bd2a-61ca8d20b673)

**Comment by ryosukemori** [comment]
@samchon 
Thank you!

I had missed it.
Now I can build comfortably.
