### ISSUE TITLE
Question: With `nestjs` official facility

### ISSUE THREAD

**Issue by starknt** [samchon/nestia#726]
## Question

Now using Nest's official CLI, `nestia` seems to work fine. I now have a working [repository](https://github.com/starknt/nestjs-offical-facility-test-with-nestia) created.

**Comment by samchon** [comment]
What do you want to ask?

**Comment by starknt** [comment]
> What do you want to ask?

It is mentioned in the [documentation](https://nestia.io/docs/setup/) that the official webpack configuration of `nest` is incompatible with `nestia`, but it seems that we can make the two work together at a small cost. Could this be a mistake? If you agree, I'll be happy to help revise the documentation. Or do you have other considerations about this issue?
