### ISSUE TITLE
SDK doesn't generate expected codebase

### ISSUE THREAD

**Issue by machendos** [samchon/nestia#755]
### Summary
Tried for few times do simple scenario with standard empty Nest.js skeleton and performed all action from corresponding page – https://nestia.io/docs/sdk/sdk/. But NPM package that is generated is not valid. There're information about entry point in the package.json: 
```typescript
"main": "lib/index.js",
```
But there're no even such a file – lib/index.js. So as a result package is unusable

There're whole project structure of generated project after performing `npm run deploy`:
<img width="357" alt="image" src="https://github.com/samchon/nestia/assets/31672085/914d5cd8-b1ed-419b-ae0d-cba1f2ecfc9a">

I believe that files that are in `lib/api/functional` are supposed to be in `lib`. But it's just an assumption

**Comment by samchon** [comment]
What can I do just with only a screenshot image? If you want help, recommend to provide the reproducible repo.

**Comment by machendos** [comment]
@samchon Here is the repo – https://github.com/machendos/nestia-sdk-bug
Commands were running after creating simple Nest.js app:
`npm i nestia`
`npx nestia setup`
`npx nestia sdk`
You can check config in `nestia.config.ts`

**Comment by samchon** [comment]
Well, the distrubition package is placed under the `src` directory.

Recommend to use another location like `packages/api`. 

If you want to keep using the `src/api2` directory, you've to configure them:

1. Ignore the `src/api2` directory in the `tsconfig.json`
2. Ignore the `src/api2` directory in the `.npmignore`
3. Ignore the `src/api2/lib` and `src/api2/node_modules` in the `.gitignore`

**Comment by machendos** [comment]
It doesn't help. Everything is the same. Pushed fixed directories in the original repository

**Comment by samchon** [comment]
You've imported DTO from controller file.

It must be separated from the server code (recommend to place DTO files under somewhere of `src/api/` (e.g. `src/api/structures`), or configure `clone` property to be `true` to make replica of the DTO structure from the controller file.
