### ISSUE TITLE
When I use generic in `@typedException` it's not work.

### ISSUE THREAD

**Issue by 8471919** [samchon/nestia#790]
### Summary
Write a short summary of the bug in here.

  - **SDK Version**: 5.2.2
  - **Expected behavior**: 
  - **Actual behavior**: 

Write detailed description in here.

### Code occuring the bug
```typescript
  // error_message
export const ERROR_MESSAGE = {
  AUTH: {
    FORBIDDEN: {
      code: 403,
      message: '금지된 접근입니다.',
    },
  },
  TOKEN: {
    NOT_FOUND_TOKEN: {
      code: 404,
      message: '토큰을 찾을 수 없습니다.',
    },
  },
} as const;

export type ErrorMessageType = {
  code: number;
  message: string;
};


// error response type
export type ErrorResponseForm<T extends ErrorMessageType> = {
  success: false;
  timestamp: string & tags.Format<'date-time'>;
  path: string & tags.Format<'url'>;
} & T;
  

  // controller.ts
  @TypedRoute.Get(['/:domainId', '/domain/:domainId'])
  @TypedException<ErrorResponseForm<typeof ERROR_MESSAGE.AUTH.FORBIDDEN>>(
    ERROR_MESSAGE.AUTH.FORBIDDEN.code,
    ERROR_MESSAGE.AUTH.FORBIDDEN.message,
  )
  @TypedException<
    ErrorResponseForm<typeof ERROR_MESSAGE.TOKEN.NOT_FOUND_TOKEN>
  >(
    ERROR_MESSAGE.TOKEN.NOT_FOUND_TOKEN.code,
    ERROR_MESSAGE.TOKEN.NOT_FOUND_TOKEN.message,
  )
  async a() {
    ...
    return res;
  }

```

when I use `@TypedException` with Type that has generic
like `@TypedException<ErrorResponseForm<T>>(args)`,
swagger docs read only last decorator generic type.
this is the example picture. (after npx nestia swagger)
![image](https://github.com/samchon/nestia/assets/27190776/97cbc4bb-264c-4786-8866-521aeb15eacf)

this is swagger.json 
![image](https://github.com/samchon/nestia/assets/27190776/75832ae9-2b98-422e-8b04-457ba3fd68f5)

you have any solution of this?

**Comment by samchon** [comment]
Seems not any problem in your example code and picture, but I may understand what you want.

If you want to define same status numbered error type multiply, just do it with union type.

```typescript
@TypedException<X|Y|Z>(403, "description")
```

**Comment by 8471919** [comment]
as looking the first picture, 403 and 404 example value's `code` and `message` is same.
that's two examples are different error each other though.
If possible, can you solve this problem?

**Comment by samchon** [comment]
Use explicit type, then no problem.
