### ISSUE TITLE
No performance difference on huge payloads

### ISSUE THREAD

**Issue by Tchekda** [samchon/nestia#799]
Hello,

My setup: NestJS + Sequelize to fetch huge payload (15k rows) with the following format: 
```ts
export interface TrackAttributes {
  id: number;
  sessionId: number;
  altitude: number;
  altitudeDifference: number;
  arrivalDistance?: number;
  bank: number;
  departureDistance?: number;
  groundSpeed: number;
  heading: number;
  latitude: number;
  longitude: number;
  onGround: boolean;
  pitch: number;
  sandbagging: boolean;
  state?: TrackState;
  timestamp: Date;
  transponder: number;
  transponderMode: string;
  time: number;
}
```
Here is the service: 
```ts
  list(sessionId: number) {
    return Track.findAll({
      where: { sessionId },
      attributes: { exclude: ['id', 'sessionId'] },
      order: [
        ['timestamp', 'ASC']
      ]
    })
  }
```
And the controller:
```ts
  @Get()
  @ApiParam({name: 'id', description: 'Session Id'})
  @ApiOkResponse({type: [PilotTrackDto], description: 'Returns all the tracks from a session'})
  list(@Param('id', new ParseIntegerPipe(false)) id: number) {
    return this.appService.list(id)
  }
```
Without Nestia, the request takes 2.5seconds total to complete, with the biggest part being the JS processing. 
We have the exact same endpoint in Rust and it takes 100ms

After quite some struggle to integrate Nestia into an existing NestJS project, I finally made it work by changing the controller to this: 
```ts
  @TypedRoute.Get()
  @ApiParam({name: 'id', description: 'Session Id'})
  @ApiOkResponse({type: [PilotTrackDto], description: 'Returns all the tracks from a session'})
  list(@Param('id', new ParseIntegerPipe(false)) id: number) {
    return this.appService.list(id)
  }
```
the results were quite deceiving: no performance gain at all, even a bit of loss. The average response time was 2.8 seconds instead of 2.5

Did I miss something during the integration (I don't think so since nestia complained about the payload not matching the interface at first) and typia was properly setup with the `npx` command ? 
Or am I in a specific where nestia doesn't perform better than usual nestjs ?

Thank you

**Comment by samchon** [comment]
Your NestJS project is not using both `class-validator` and `class-transformer`, so that no merit for performance side. In contracty, on the Nestia side, it performs validation abouot the returning value before JSON serialization, so that it can be slower.

**Comment by samchon** [comment]
As I've mentioned in the previous comment, I can't see how about the `TrackState` type.

Anyway, as you're not utilizing `class-transformer` and just returning the raw value not following the NestJS guide, your NestJS program vs Nestia program is similar with `express-pure` vs `express-typia` case. In the most case, `express-typia` is faster, but there're some cases that `express-pure` is faster than the `express-typia` case.

![Server side stringify](https://raw.githubusercontent.com/samchon/typia/master/benchmark/results/AMD%20Ryzen%209%207940HS%20w%20Radeon%20780M%20Graphics/images/server-stringify.svg)

> https://github.com/samchon/typia/tree/master/benchmark/results/AMD%20Ryzen%209%207940HS%20w%20Radeon%20780M%20Graphics#server-stringify

**Comment by Tchekda** [comment]
Hi @samchon thank you very much for replying.

TrackState is a String enum.

Is there any way to force nestjs to use the classes to improve performances or it won't change anything in my case ?

From the Nestia TypedRoute documentation, I see that you are importing typia to set rules on the output payload whereas I'm just trying to speed up my serialization process.

Thank you

**Comment by samchon** [comment]
No, if you utilize `class-transformer` based class instance for returning following the NestJS formal guide documents, the performance becomes extremely slower as you can see from the above reply's benchmark graph. In your case, just keep using the `@Get()` or `@Post()` decorator (instead, you must ensure the returned value is exactly keeping the promised type), then no problem.

**Comment by samchon** [comment]
Upgrade to `typia@5.4.11`, then performance would be a little bit faster.

**Comment by Tchekda** [comment]
> Upgrade to `typia@5.4.11`, then performance would be a little bit faster.

@samchon sadly it hasn't changed a bit, the results are exactly the same with `"typia": "^5.4.11"`

**Comment by Tchekda** [comment]
About the sequelize variable issue you are mentioning, I record the time it takes to run `await this.appService.list(id)` and it's around 110ms, so really small compared to the 2900ms the request takes to complete. 
Sequelize might have been the variable issue but it's not the case here

**Comment by samchon** [comment]
```typescript
import typia from "typia";

interface TrackAttributes {
  id: number;
  sessionId: number;
  altitude: number;
  altitudeDifference: number;
  arrivalDistance?: number;
  bank: number;
  departureDistance?: number;
  groundSpeed: number;
  heading: number;
  latitude: number;
  longitude: number;
  onGround: boolean;
  pitch: number;
  sandbagging: boolean;
  state?: number;
  timestamp: Date;
  transponder: number;
  transponderMode: string;
  time: number;
}

const REPEAT = 100_000
const data: TrackAttributes = typia.random<TrackAttributes>();
const fn = typia.json.createStringify<TrackAttributes>();

console.time("typia.json.stringify");
new Array(REPEAT).fill(0).map(() => fn(data));
console.timeEnd("typia.json.stringify");

console.time("JSON.stringify");
new Array(REPEAT).fill(0).map(() => JSON.stringify(data));
console.timeEnd("JSON.stringify");
```

> ```bash
> typia.json.stringify: 175.716ms
> JSON.stringify: 408.235ms
> ```

Tested your code, and no problem.

**Comment by samchon** [comment]
Even when the `REPEAT` count be reduced to `1_000`, `typia.json.stringify()` is still faster.

```bash
typia.json.stringify: 3.533ms
JSON.stringify: 7.195ms
```

It is possible to make `typia` slower than configuring the `REPEAT` value much lesser, but I think it doesn't mean.

**Comment by samchon** [comment]
If the `typia.json.assertStringify()` function used like `@TypedRoute`:

### REPEAT is 100,000

```bash
typia.json.stringify: 256.439ms
JSON.stringify: 435.498ms
```

### REPEAT is 1,000
```bash
typia.json.stringify: 4.93ms
JSON.stringify: 5.919ms
```

**Comment by Tchekda** [comment]
Indeed you are right. 
Here is my code with some timing debug: 
```ts
console.time('list');
const data = await this.appService.list(id);
console.timeEnd('list');
console.time('stringify');
const fn = typia.json.createStringify<TrackAttributes[]>();
const resStr = fn(data);
console.timeEnd('stringify');
console.time('send');
res.send(resStr);
console.timeEnd('send');
```
And the results are:
```
list: 165.33ms
stringify: 28.204ms
send: 8.899ms
```
Now I am really confused on what might be causing this issue. 

Thank you very much for trying to help me, appreciated

**Comment by Tchekda** [comment]
For those that might find this issue while trying to optimize their endpoints. 
In our case it came from brotli compression and wrongfully blamed the serialization process. Sorry about that
Refererence: https://github.com/nestjs/docs.nestjs.com/issues/2834#issuecomment-1962943530
