### ISSUE TITLE
I want to use `@TypedException` with same statusCode, differenct Error message. (`@TypedException` doesn't work with object union type)

### ISSUE THREAD

**Issue by 8471919** [samchon/nestia#816]
### Summary
Write a short summary of the bug in here.

  - **SDK Version**: 2.5.8
  - **Expected behavior**: 
  - **Actual behavior**: 

In `npx nestia swagger`.
when I use union type of object type, `@TypedExeption` doesn't make swagger document.
```typescript
interface A {
  code: 1;
  message: 'hi';
}
interface B {
  code: 2;
  message: 'hello';
}

@TypedException<A | B>(200)
async func() {
  ...
}
```
Exception is not displayed on the swagger document.

### Code occuring the bug

Exactly I want to use `@TypedException` this way,
```typescript
namespace ERROR_MESSAGE {
  export interface USER_NOT_FOUND {
    code: 404;
    message: "Can not find user";
  }

  export interface USER_INFO_NOT_FOUND {
    code: 404;
    message: "No User info";
  }
}

@TypedException<ERROR_MESSAGE.USER_NOT_FOUND | ERROR_MESSAGE.USER_INFO_NOT_FOUND>(404)
@Get('user-info')
async getUserInfo() {
  return userInfo;
}

```

but, Union type doesn't work about object union type.
![image](https://github.com/samchon/nestia/assets/27190776/b0e5932c-a934-48cf-a15c-bc4bb71dd580)
this is the result of above code. Here is no exception description.

and this not work too.
```typescript
@TypedException<ERROR_MESSAGE.USER_NOT_FOUND>(404)
@TypedException<ERROR_MESSAGE.USER_INTO_NOT_FOUND>(404)
@Get('user-info')
async getUserInfo() {
  return userInfo;
}
```
and I want for you to make this using "oneOf" of swagger.

**Comment by rojiwon123** [comment]
Looks like there's a bug related to the code I previously contributed! I'll go ahead and make the necessary fixes to the code and add some test cases.

**Comment by rojiwon123** [comment]
This error occurs during the "DO ASSIGN" process in the ExceptionAnalyzer module. The exception cases are as follows:

- When the exception schema is a union type, and each sub-type is an object type using hierarchical type names, differences in type name representation can occur, causing mismatches. For example, if the type name is `ErrorCode.NotFound`, in a tuple it will be fully represented while in func.exceptions only `NotFound` might be indicated.

- When the exception schema is in generic form, the type names are not appropriately split. Currently, a simple split and sort operation is performed based on the " | " delimiter in the entire string. In this process, if there's a type like Gen<101 | 202>, it might be split into "Gen<101" and "202>", causing issues with proper type name comparison.

Moreover, when the exception schema is generic, it's necessary to ensure that the imports of the types injected as generics are done correctly. For example, if there's a type name like Exception<NotFound | Unauthorize>, the Exception type, NotFound type, and Unauthorized type should each be imported correctly.
