### ISSUE TITLE
How about to use the "examples" function of Swagger? for convenience to front-end developer?

### ISSUE THREAD

**Issue by 8471919** [samchon/nestia#820]
I always feel thank for you to make this great library.

This function that I will suggest from now is not necessary function. but It makes that the better User Experience.

currently, if we want to use two responses from same status code, the swagger makes the two responses belong to only "oneOf" option.
but, If you make that responses belong to also "examples" option, the user (especially front-end developer) can see the responses clearly as follow.

![image](https://github.com/samchon/nestia/assets/27190776/efdd432b-9df2-42fe-a43e-83ae70010743)

![image](https://github.com/samchon/nestia/assets/27190776/78314e2d-eb7b-465f-8d81-6fb75dd4b4b9)

![image](https://github.com/samchon/nestia/assets/27190776/7aeb59e4-5b8e-4a91-a1d8-99051e73598f)

![image](https://github.com/samchon/nestia/assets/27190776/bf746aab-4d5f-4288-81cd-e5aec95ac3b5)

**Comment by samchon** [comment]
It is possible to support swagger examples.

By the way, do you think that the examples should be put into the SDK?

**Comment by 8471919** [comment]
> It is possible to support swagger examples.
> 
> By the way, do you think that the examples should be put into the SDK?

What you mean is to put true or false option of the 'examples' in `nestia.config.ts`?

I can't imagine how will you put the "examples" in SDK.

**Comment by samchon** [comment]
```typescript
/**
 * Store an article.
 *
 * @param input Content to store
 * @returns Newly archived article
 * @deprecated
 *
 * @controller BbsArticlesController.store
 * @path POST /bbs/articles
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function store(
  connection: IConnection,
  input: store.Input,
): Promise<store.Output> {
  return PlainFetcher.fetch(
    {
      ...connection,
      headers: {
        ...connection.headers,
        "Content-Type": "application/json",
      },
    },
    {
      ...store.METADATA,
      path: store.path(),
    },
    input,
  );
}
export namespace store {
  export type Input = Primitive<IBbsArticle.IStore>;
  export type Output = Primitive<IBbsArticle>;

  export const METADATA = {
    method: "POST",
    path: "/bbs/articles",
    request: {
      type: "application/json",
      encrypted: false,
    },
    response: {
      type: "application/json",
      encrypted: false,
    },
    status: null,
  } as const;

  export const path = () => "/bbs/articles";

  export const EXAMPLES: Output[] = [...];
}
```

Something like this.

**Comment by samchon** [comment]
I will check the propagate type again.

By the way, how to write the example data in the method? Do you have any idea?

**Comment by 8471919** [comment]
> I will check the propagate type again.
> 
> By the way, how to write the example data in the method? Do you have any idea?

I think the "Example" of sdk should utilize as type rather than value. because It's so hard to use only type of result, and the input of "Example" is originally type.
It's so convenient if I can get return type like `api.typical.bbs.article.store.status<404>.Example` or `api.typical.bbs.article.store.Example<statusCode>`

```typescript
// api/typical/bbs/article
export namespace store {
  export type Example<T> = T extends 404
    ? {code: 404, message: "no articles here"} | {code: 404, message: "no bbs here"}
    : T extends 400
      ? ...etc
}

// front
type ResponseError<T> = api.typical.bbs.article.store.Example<T>

try {
  const res = await api.functional.bbs.article.store(url)
  ...
} catch (err) {
  const errorData: ResponseError<typeof err.statusCode>;
  ...
}

```
