### ISSUE TITLE
Issue with assignHeaders and setHeader

### ISSUE THREAD

**Issue by masterr115** [samchon/nestia#824]
## Question
Hello, I'm trying to integrate the assignHeaders and setHeader methods, but I'm having errors when compiling for the SDK.

I want to use the token extracted from the login for the rest of the application. 

### This is my login route

![image](https://github.com/samchon/nestia/assets/62192450/9e3d8285-990e-4982-b291-cddf0ae82a7d)

### This is my interface (ILoginResponse)

![image](https://github.com/samchon/nestia/assets/62192450/b4680611-cbcb-49b3-8d72-f4780981e613)

----

And I would like to use the header that was taken from the Auth route within other methods, such as creating a group

### Group creation route
![image](https://github.com/samchon/nestia/assets/62192450/aee081b7-c536-4d57-9edb-657c33ffc0da)

### Group creation interface response

![image](https://github.com/samchon/nestia/assets/62192450/18b044e5-cbf3-4181-bc26-3073c94595ee)

How could this integration be done?

----

### ERROR:

![image](https://github.com/samchon/nestia/assets/62192450/6ab3b064-ddd8-40ab-b06f-772406a5f817)

**Comment by samchon** [comment]
Don't upload screenshot, but a reproducible repo please.

**Comment by masterr115** [comment]
> Don't upload screenshot, but a reproducible repo please.

I've just created gist for it with these files.

https://gist.github.com/masterr115/799424fd6be54f0a239243d9e9dd89e8
