### ISSUE TITLE
Can transform Atomic value to array?

### ISSUE THREAD

**Issue by sacru2red** [samchon/nestia#831]
## Question

When using TypedQuery, I want to get some array values.

It works in other cases , but not element is atomic
so, I want to transform atomic to array

```
/**
 * @TypedQuery() query: { someArrayExceped: number[] }
*/
// It works { someArrayExpected: [1, 2] } 
https://domain.com/foo-controller/bar-route?someArrayExpected=1&someArrayExpected=2
// but got { someArrayExpected: 1 }, I want to get { someArrayExpected: [1] }
https://domain.com/foo-controller/bar-route?someArrayExpected=1
```

**Comment by samchon** [comment]
As `@nestia/core` calls the `URLSearchParams.getAll()` method for the array type, your problem can't be.

Here is the example project that demonstrating there's not any problem on the `@TypedQuery()`.

https://stackblitz.com/edit/stackblitz-starters-nkmslk?file=src%2Findex.ts
