### ISSUE TITLE
Nestjs fastify use NestInterceptor auto stringify

### ISSUE THREAD

**Issue by zaohuayudie** [samchon/nestia#868]
## Bug Report
Nestjs+Fastify, the return value is a string, and the expectation is json
```
controller.ts
@TypedRoute.Get('config')
async test() {
    return { name: 'zaohua', img: ''}
}

When I use TransformInterceptor:

import {
  CallHandler,
  ExecutionContext,
  Injectable,
  NestInterceptor,
} from '@nestjs/common';
import { map, Observable } from 'rxjs';
import { FastifyReply } from 'fastify';

interface Response<T> {
  data: T;
}

@Injectable()
export class TransformInterceptor<T>
  implements NestInterceptor<T, Response<T>>
{
  intercept(context: ExecutionContext, next: CallHandler): Observable<any> {
    const res = context.switchToHttp().getResponse<FastifyReply<any>>();
    res.header('Content-Type', 'application/json; charset=utf-8');
    return next.handle().pipe(
      map((data) => {
        return {
          data,
          code: 0,
          msg: '请求成功',
        };
      }),
    );
  }
}


GET or Post response data is string
{
  "data": "{\"name\":\"zaohua\",\"img\":\"\"}",
  "code": 0,
  "msg": "请求成功"
}
```

### Summary
Write a short summary of the bug in here.

  - **SDK Version**:  2.6.4
  - **Expected behavior**:  data is json, {"name": "zaohua", "img":""}
  - **Actual behavior**:  data is string, "{\"name\":\"zaohua\", \"img\":\"\"}"

the same question : https://stackoverflow.com/questions/76884219/disable-nestinterceptor-auto-stringify

**Comment by samchon** [comment]
`@TypedRoute()` ensures type safety and boosts up serialization through `typia.json.assertStringify()` funtion. 

Therefore, it is not possible to change the response object through the global interceptor, and it is intended spec of the `@TypedRoute()`: the responded object type must be same with its DTO type. If you don't want that, you have to use original `@Post()` or `@Get()` function of `nestjs`.

**Comment by zaohuayudie** [comment]
> `@TypedRoute()` ensures type safety and boosts up serialization through `typia.json.assertStringify()` funtion.
> 
> Therefore, it is not possible to change the response object through the global interceptor, and it is intended spec of the `@TypedRoute()`: the responded object type must be same with its DTO type. If you don't want that, you have to use original `@Post()` or `@Get()` function of `nestjs`.

Thanks!
