### ISSUE TITLE
[Question or Bug Report] decompose option's bug on swagger generator with special tags, defined anonymous interface.

### ISSUE THREAD

**Issue by rojiwon123** [samchon/nestia#908]
## Description

When I build a swagger document in decompose mode, the special tag information I defined in the query's attributes is not applied to the swagger document. Is this the intended behavior? If not, I think I have found a bug.

```ts
 @core.TypedRoute.Get()
    async getList(
        @core.TypedQuery()
        query: { start_date: string & typia.tags.Format<"date-time">, end_date: string & typia.tags.Format<"date-time"> },
    ): Promise<IUser[]> {
        return this.usecase.getList(query.start_date, query.end_date);
    }
```
```json
{
    "name": "start_date",
    "in": "query",
    "schema": {},
    "required": true
},
```

version info.

"@nestia/sdk": "^3.2.0",
"@nestia/core": "^3.2.0",
"typescript": "^5.4.5",

**Comment by rojiwon123** [comment]
This only happens when using an anonymous interface.

**Comment by samchon** [comment]
It's because `nestia` does not allow unnamed type (literal expression type).
