### ISSUE TITLE
Is there an reason to  `config.swagger.decompose` defaults to false?

### ISSUE THREAD

**Issue by hikinine** [samchon/nestia#943]
Greetings, amazingg library. 
I am using combined with [Orval](https://orval.dev/guides/react-query) which takes que generated openapi json and convert into react-query 

Anyway, i was supposed to drop the library because the only way i found (before hear about decompose option) to "properly" use @TypedQuery was replacing via script the generated `openapi.json`.

Diving on docs, i was not able to find any reference to "decompose".
luck for me, i was looking old issues and found https://github.com/samchon/nestia/issues/612 which was exactly what I need.

## OPTION 1 (default)
![image](https://github.com/samchon/nestia/assets/30875229/fb4ac854-9a4e-4f31-8eee-ba73e385abbf)

## OPTION 2 (desired)
![image](https://github.com/samchon/nestia/assets/30875229/5d5477a3-b144-4521-85b8-25be9e4f320e)

I am 100% sure that exists an usecase where people would prefer `option 1`. I just dont think it should be an default option. Am I wrong?

Thanks in advance

**Comment by samchon** [comment]
I had configured it to `false` because the query parameter name can be duplicated with path parameter name.

If you have other insight, then tell me please. Changing the default value is not hard thing.

**Comment by samchon** [comment]
Also, I'll enhance the document at next week.

**Comment by hikinine** [comment]
Duplicated param/query may be a valid concern.
I'm not in a position to evaluate whether defaulting to `true` is the best option, as I don't know the exact side effects.

Anyway, If no one has bothered with this yet...
Enhance and highlight it to docs may be enough.

Again, amazing lib
