### ISSUE TITLE
Swagger generation error on Implicit controller method return types

### ISSUE THREAD

**Issue by nezudevv** [samchon/nestia#974]
### Summary
On newest Nestia version `3.9.0` when generating swagger docs using `npx nestia swagger` I get the following error: 
```
[Nest] 17066  - 07/29/2024, 11:04:55 PM     LOG [NestFactory] Starting Nest application...
[Nest] 17066  - 07/29/2024, 11:04:55 PM     LOG [InstanceLoader] StatusModule dependencies initialized...
Analyzing reflections
  - controllers: #3
  - paths: #3
  - routes: #3
Analyzing source codes
Error: NestiaApplication.swagger(): implicit return type is not allowed.

List of implicit return typed routes:
  - StatusController.get at "src/status/status.controller.ts:12:66"
  - ShipmentController.findById at "src/shipment/shipment.controller.ts:7:70"
    at NestiaSdkApplication.<anonymous> (redacted/nestjs/node_modules/@nestia/sdk/src/NestiaSdkApplication.ts:257:15)
    at Generator.next (<anonymous>)
    at fulfilled (redacted/nestjs/node_modules/@nestia/sdk/lib/NestiaSdkApplication.js:28:58)
```

  - **SDK Version**:  "@nestia/sdk": "^3.9.0",
  - **Expected behavior**: "The swagger generation cli command should ignore implicit typed controller methods.
  - **Actual behavior**: The swagger cli command errors out if there is an implicit type controller method.

Write detailed description in here.

After first updating, the command DID work. However, I deleted the existing `swagger.json` file to test a fresh file being generated and that is when the error occured.

### Code where the bug is occuring:
```typescript
@Controller('status-nest')
export class StatusController {
    constructor(private readonly statusService: StatusService) {}

    /**
     * Retrieves the status of the service.
     * This service can be used for health checks.
     */
    @TypedRoute.Get()
    get() {
        return this.statusService.get();
    }
}
```

**Comment by samchon** [comment]
Upgrade both `typia` and `@nestia/*` to be latest. Then you can generate swagger document even in the implicit types.

Also, I saw your another question about SDK generation on implicit type. You can do it if you configure `clone` property to be `true` in the `nestia.config.ts` file.

https://nestia.io/docs/sdk/sdk/#clone-mode

**Comment by nezudevv** [comment]
@samchon Ahh, I missed updating one dependency. Sorry about that! 
It works now, I really appreciate it. Do you have this project open for contributors? This is a great tool and i'd like to contribute to it once I have some time.

Thanks!

**Comment by samchon** [comment]
This project is always opened.
