### ISSUE TITLE
Cannot build on @nestia/sdk@3.11.0

### ISSUE THREAD

**Issue by sacru2red** [samchon/nestia#994]
### Summary
Write a short summary of the bug in here.

  - **SDK Version**: 3.11.0
  - **Expected behavior**: working 
  - **Actual behavior**: swagger generator is dead

Write detailed description in here.

nestia.config.ts
```ts
import type nestia from '@nestia/sdk'

export const NESTIA_CONFIG = {
  input: {
    include: ['./src/**/*.controller.ts', './src/presentation/**/*.ts'],
  },
  output: './src/api',
  swagger: {
    output: './swagger/swagger.json',
    security: {
      bearer: {
        type: 'http',
        scheme: 'bearer',
        bearerFormat: 'JWT',
      },
    },
  },
} satisfies nestia.INestiaConfig
export default NESTIA_CONFIG

```

@nestia/sdk@3.10.0 works but not 3.11.0

nestia sdk generate dead
```
$ npx nestia swagger
-----------------------------------------------------------
 Nestia Swagger Generator
-----------------------------------------------------------
```

(before logging "Analyzing reflections")

### Code occuring the bug
```typescript
/* Demonstration code occuring the bug you're reporting */
```

Write the demonstration code occuring the bug you're reporting.

However, as the `nestia` is not a typical library who being used by the `import` statement but a executable program generating the SDK (Software Development Kit), it would be difficult to describe the bug with only the demonstration code.

In that case, you'd better to make a demonstration project occuring the bug to report. After the demonstration repository composition, fill the below `bash` script section. Of course, if you can describe the bug clearly, without the demonstration project construction, just skip it. Creating the demonstration repository is not essential.

```bash
git clone https://github.com/someone/nestia-bug-report-xxx
cd nestia-bug-report-xxx
npx nestia sdk
```

**Comment by samchon** [comment]
Reproducible repo?

**Comment by znycheporuk** [comment]
I also faced this issue. Here is an example repository:

[https://github.com/znycheporuk/nestia](https://github.com/znycheporuk/nestia)

**Comment by sacru2red** [comment]
@samchon 
늦었지만 재현가능한 레포를 만들었습니다.

https://github.com/sacru2red/nestia-build-fail

**Comment by sacru2red** [comment]
음..

### Not works
```
input: {
    include: ['./src/**/*.controller.ts'],
  },
```

### Works
```
input: async () => {
    const app = await NestFactory.create(AppModule);
    return app;
  },
```

**Comment by samchon** [comment]
Traveled your code, and found the reason.

At first, you have to setup `ts-patch`. Just run the `npx nestia setup` command.

The second problem is, as you've written like above comment, the dynamic module importing by location path no more works. NestJS application module is blocking it. Therefore, I also need to take a major update that allowing only function typed input configurion like `input: () => NestFactory.create(AppModule)`.

About the second problem, I'll take a major update ASAP.

**Comment by sacru2red** [comment]
@samchon 

I'am trying with 
```
input: async () => {
    const app = await NestFactory.create(AppModule);
    return app;
  },
```

but got error in my project at
```
@Module({
  imports: [
    ConfigModule.forRoot({
      isGlobal: true,
      expandVariables: true,
      validationSchema: Joi.object({
        NODE_ENV: Joi.string().valid('dev', 'prod').required(),
        MARIA_DB_HOST: Joi.string().required(),
        MARIA_DB_PORT: Joi.number().required(),
        MARIA_DB_USERNAME: Joi.string().required(),
        MARIA_DB_PASSWORD: Joi.string().required(),
        MARIA_DB_DATABASE: Joi.string().required(),
      }),
    }),
```

```
Error: Config validation error: "NODE_ENV" is required
    at Function.forRoot (C:\Users\smartbig\Desktop\svn\bodumcareServer\api-v2.bodumcare.com\node_modules\@nestjs\config\dist\config.module.js:86:23)
    at Object.<anonymous> (C:\Users\smartbig\Desktop\svn\bodumcareServer\api-v2.bodumcare.com\src\app.module.ts:73:18)
    at Module._compile (node:internal/modules/cjs/loader:1358:14)
    at Module.m._compile (C:\Users\smartbig\Desktop\svn\bodumcareServer\api-v2.bodumcare.com\node_modules\ts-node\src\index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
    at Object.require.extensions.<computed> [as .ts] (C:\Users\smartbig\Desktop\svn\bodumcareServer\api-v2.bodumcare.com\node_modules\ts-node\src\index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1208:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1024:12)
    at Module.require (node:internal/modules/cjs/loader:1233:19)
    at require (node:internal/modules/helpers:179:18)
```

do you know any solution?

**Comment by samchon** [comment]
Then try to find another way to keep the dynamic controller importing way by location path.

**Comment by samchon** [comment]
Upgrade to `3.11.2` patch version, then your problem be fixed.

Thanks for reporting.
